"""Validate SKILL.md skill mentions and parent-path rules."""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

# Skill names that are allowed to reference ../../.githooks/ in addition to ../references and ../../tools
_EXTENDED_PARENT_EXCEPTIONS = {"update-skill-guidelines"}

# Pattern: a relative path segment that goes upward (../.. or higher)
_PARENT_PATH_RE = re.compile(r"(?:^|(?<=[^A-Za-z0-9_./~\-]))(?:\.\.?/)*\.\./")
_ALLOWED_DIRS_BASE = re.compile(
    r"(?:^|(?<=[^A-Za-z0-9_./~\-]))(?:\.\.?/)*\.\./(?:references|tools|scripts)(?:/|[ \t`'\"]|$)"
)
_ALLOWED_DIRS_EXTENDED = re.compile(
    r"(?:^|(?<=[^A-Za-z0-9_./~\-]))(?:\.\.?/)*\.\./(?:references|tools|scripts|\.githooks)(?:/|[ \t`'\"]|$)"
)

_DEPRECATED_MARKERS_RE = re.compile(r"^(Sub-skills to invoke:|Depends on:)", re.MULTILINE)
_FRONTMATTER_RE = re.compile(r"^---\s*\n.*?\n---\s*\n", re.DOTALL)

_BLUEPRINT_BLOCK_RE = re.compile(
    r"<!-- BEGIN BLUEPRINT (?:CONTRACT|INTERFACES) -->.*?<!-- END BLUEPRINT (?:CONTRACT|INTERFACES) -->",
    re.DOTALL,
)


def _strip_frontmatter_and_deps(text: str) -> str:
    """Return SKILL.md text without frontmatter or generated blueprint blocks."""
    # Strip frontmatter
    fm_match = _FRONTMATTER_RE.match(text)
    if fm_match:
        text = text[fm_match.end():]

    # Strip generated blueprint blocks (autogenerated — not hand-authored body)
    text = _BLUEPRINT_BLOCK_RE.sub("", text)

    return text


def _word_boundary_mentions(text: str, skill_name: str) -> bool:
    """Return True if skill_name appears as a whole token in text."""
    escaped = re.escape(skill_name)
    pattern = re.compile(
        r"(?:^|(?<=[^A-Za-z0-9:_\-]))" + escaped + r"(?=[^A-Za-z0-9:_\-]|$)"
    )
    return bool(pattern.search(text))


def _load_blueprint_used_skills(path: Path) -> list[str]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(raw, dict):
        return []
    interfaces = raw.get("interfaces") or {}
    if not isinstance(interfaces, dict):
        return []
    used: set[str] = set()
    for namespace in ("machine", "llm"):
        specs = interfaces.get(namespace) or {}
        if not isinstance(specs, dict):
            continue
        for spec in specs.values():
            if not isinstance(spec, dict):
                continue
            for entry in spec.get("uses_interfaces", []) or []:
                if not isinstance(entry, dict):
                    continue
                target = entry.get("interface")
                if not isinstance(target, str):
                    continue
                parts = target.split(".")
                if len(parts) == 3 and parts[0]:
                    used.add(parts[0])
    return sorted(used)


def _validate_parent_paths(skill_file: Path, skill_name: str) -> list[str]:
    errors: list[str] = []
    allowed = _ALLOWED_DIRS_EXTENDED if skill_name in _EXTENDED_PARENT_EXCEPTIONS else _ALLOWED_DIRS_BASE
    for lineno, line in enumerate(skill_file.read_text(encoding="utf-8").splitlines(), start=1):
        if _PARENT_PATH_RE.search(line) and not allowed.search(line):
            errors.append(
                f"{skill_file}:{lineno}: parent paths in SKILL.md may only point to "
                f"../references or ../../tools: {line.strip()}"
            )
    return errors


def validate(repo_root: Path) -> list[str]:
    errors: list[str] = []
    skills_root = repo_root / "skills"
    if not skills_root.is_dir():
        return errors

    # Collect all known skill names from local skill directories and interface uses.
    skill_name_set: set[str] = {p.name for p in skills_root.iterdir() if p.is_dir()}
    for blueprint in skills_root.glob("*/blueprint.yaml"):
        skill_name_set.update(_load_blueprint_used_skills(blueprint))
    skill_names = sorted(skill_name_set)

    skill_files = sorted(skills_root.glob("*/SKILL.md"))

    # Pass 1: parent-path checks
    for skill_file in skill_files:
        skill_name = skill_file.parent.name
        errors.extend(_validate_parent_paths(skill_file, skill_name))

    # Pass 2: skill mention checks
    for skill_file in skill_files:
        skill_dir = skill_file.parent
        skill_name = skill_dir.name
        blueprint_file = skill_dir / "blueprint.yaml"

        text = skill_file.read_text(encoding="utf-8")

        # Check for deprecated markers
        for m in _DEPRECATED_MARKERS_RE.finditer(text):
            lineno = text[: m.start()].count("\n") + 1
            errors.append(
                f"{skill_file}:{lineno}: {m.group(0)} — "
                f"declare cross-skill use through blueprint.yaml `uses_interfaces`"
            )

        blueprint_uses = _load_blueprint_used_skills(blueprint_file) if blueprint_file.exists() else []

        # Extract exact skill-name mentions in body
        body = _strip_frontmatter_and_deps(text)
        other_skills = sorted(s for s in skill_names if s != skill_name)
        body_mentions = sorted(s for s in other_skills if _word_boundary_mentions(body, s))
        undeclared_mentions = sorted(set(body_mentions) - set(blueprint_uses))

        if undeclared_mentions:
            errors.append(
                f"{skill_file}: exact skill-name mentions in SKILL.md body are not declared "
                f"through {blueprint_file}:interfaces.*.*.uses_interfaces: {undeclared_mentions}"
            )

    return errors


def main() -> int:
    errors = validate(Path(__file__).resolve().parents[3])
    if errors:
        print("error: invalid skill dependencies.", file=sys.stderr)
        for error in errors:
            print(f"  {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
