"""Validate SKILL.md skill mentions and parent-path rules."""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

_REPO_ROOT = Path(__file__).resolve().parents[3]
_SRC_ROOT = _REPO_ROOT / "src"
if str(_SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(_SRC_ROOT))

from officina.common.blueprint_graph import (  # noqa: E402
    BlueprintGraphError,
    load_skill_blueprint_graph,
)

# Skill names that are allowed to reference ../../.githooks/ in addition to ../references and ../../tools
_EXTENDED_PARENT_EXCEPTIONS = {"update-skill-guidelines"}

# Pattern: a relative path segment that goes upward (../.. or higher)
_PARENT_PATH_RE = re.compile(r"(?:^|(?<=[^A-Za-z0-9_./~\-]))(?:\.\.?/)*\.\./")
_ALLOWED_DIRS_BASE = re.compile(
    r"(?:^|(?<=[^A-Za-z0-9_./~\-]))(?:\.\.?/)*\.\./(?:references|tools|scripts)(?:/|[ \t`'\"]|$)"
)
_ALLOWED_DIRS_EXTENDED = re.compile(
    r"(?:^|(?<=[^A-Za-z0-9_./~\-]))(?:\.\.?/)*\.\./(?:references|tools|scripts|\.githooks)(?:/|[ \t`'\"]|$)"
)

_DEPRECATED_MARKERS_RE = re.compile(r"^(Sub-skills to invoke:|Depends on:)", re.MULTILINE)
_FRONTMATTER_RE = re.compile(r"^---\s*\n.*?\n---\s*\n", re.DOTALL)

_BLUEPRINT_BLOCK_RE = re.compile(
    r"<!-- BEGIN BLUEPRINT (?:CONTRACT|INTERFACES) -->.*?<!-- END BLUEPRINT (?:CONTRACT|INTERFACES) -->",
    re.DOTALL,
)
_CANONICAL_INTERFACE_RE = re.compile(
    r"\b[a-z0-9]+(?:-[a-z0-9]+)+\.(?:llm|machine)\.[a-z0-9]+(?:-[a-z0-9]+)*\b"
)
_OPAQUE_RUNTIME_PATH_RE = re.compile(
    r"(?<![A-Za-z0-9_./~-])(?:[A-Za-z0-9_.~+-]+/)*_(?:rtx|cx)/[A-Za-z0-9_.~+/-]+"
)


def _strip_frontmatter_and_deps(text: str) -> str:
    """Return SKILL.md text without frontmatter or generated blueprint blocks."""
    # Strip frontmatter
    fm_match = _FRONTMATTER_RE.match(text)
    if fm_match:
        text = text[fm_match.end():]

    # Strip generated blueprint blocks (autogenerated — not hand-authored body)
    text = _BLUEPRINT_BLOCK_RE.sub("", text)

    return text


def _word_boundary_mentions(text: str, skill_name: str) -> bool:
    """Return True if skill_name appears as a whole token in text."""
    escaped = re.escape(skill_name)
    pattern = re.compile(
        r"(?:^|(?<=[^A-Za-z0-9:_\-]))" + escaped + r"(?=[^A-Za-z0-9:_\-]|$)"
    )
    return bool(pattern.search(text))


def _load_blueprint_used_skills(path: Path) -> list[str]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(raw, dict):
        return []
    if raw.get("schema_version") == 2 or "blueprint_type" in raw:
        try:
            graph = load_skill_blueprint_graph(path.parent)
        except BlueprintGraphError:
            return []
        used = {
            edge.target_id.split(".", 1)[0]
            for edge in graph.edges
            if edge.relation == "uses-interface"
        }
        return sorted(used)
    interfaces = raw.get("interfaces") or {}
    if not isinstance(interfaces, dict):
        return []
    used: set[str] = set()
    for namespace in ("machine", "llm"):
        specs = interfaces.get(namespace) or {}
        if not isinstance(specs, dict):
            continue
        for spec in specs.values():
            if not isinstance(spec, dict):
                continue
            for entry in spec.get("uses_interfaces", []) or []:
                if not isinstance(entry, dict):
                    continue
                target = entry.get("interface")
                if not isinstance(target, str):
                    continue
                parts = target.split(".")
                if len(parts) == 3 and parts[0]:
                    used.add(parts[0])
    return sorted(used)


def _validate_typed_body_interfaces(
    graph: object,
    known_skill_names: set[str],
) -> list[str]:
    errors: list[str] = []
    for node in graph.nodes.values():
        if node.blueprint_type not in {"llm-interface", "behavior-source"}:
            continue
        if node.binding_path is None:
            continue
        try:
            body = _strip_frontmatter_and_deps(
                node.binding_path.read_text(encoding="utf-8")
            )
        except UnicodeDecodeError:
            continue
        for match in _OPAQUE_RUNTIME_PATH_RE.finditer(body):
            errors.append(
                f"{node.binding_path}: typed {node.blueprint_type} body names opaque "
                f"runtime path `{match.group(0)}`; use a declared canonical machine interface"
            )
        declared = {
            entry.get("interface")
            for entry in node.declaration.get("uses_interfaces", [])
            if isinstance(entry, dict) and isinstance(entry.get("interface"), str)
        }
        mentioned_interfaces = set(_CANONICAL_INTERFACE_RE.findall(body))
        for interface_id in sorted(mentioned_interfaces - declared):
            errors.append(
                f"{node.binding_path}: canonical interface `{interface_id}` is not declared "
                f"in {node.node_id}.uses_interfaces"
            )

        prose_without_interfaces = _CANONICAL_INTERFACE_RE.sub("", body)
        owner_skill = node.node_id.split(".", 1)[0]
        bare_names = sorted(
            skill_name
            for skill_name in known_skill_names
            if skill_name != owner_skill
            and _word_boundary_mentions(prose_without_interfaces, skill_name)
        )
        if bare_names:
            errors.append(
                f"{node.binding_path}: typed {node.blueprint_type} bodies must use canonical "
                f"interface IDs instead of bare skill names: {bare_names}"
            )
    return errors


def _validate_parent_paths(skill_file: Path, skill_name: str) -> list[str]:
    errors: list[str] = []
    allowed = _ALLOWED_DIRS_EXTENDED if skill_name in _EXTENDED_PARENT_EXCEPTIONS else _ALLOWED_DIRS_BASE
    for lineno, line in enumerate(skill_file.read_text(encoding="utf-8").splitlines(), start=1):
        if _PARENT_PATH_RE.search(line) and not allowed.search(line):
            errors.append(
                f"{skill_file}:{lineno}: parent paths in SKILL.md may only point to "
                f"../references or ../../tools: {line.strip()}"
            )
    return errors


def validate(repo_root: Path) -> list[str]:
    errors: list[str] = []
    skills_root = repo_root / "skills"
    if not skills_root.is_dir():
        return errors

    # Collect all known skill names from local skill directories and interface uses.
    skill_name_set: set[str] = {p.name for p in skills_root.iterdir() if p.is_dir()}
    for blueprint in skills_root.glob("*/blueprint.yaml"):
        skill_name_set.update(_load_blueprint_used_skills(blueprint))
    skill_names = sorted(skill_name_set)

    skill_files = sorted(skills_root.glob("*/SKILL.md"))

    # Pass 1: parent-path checks
    for skill_file in skill_files:
        skill_name = skill_file.parent.name
        errors.extend(_validate_parent_paths(skill_file, skill_name))

    # Pass 2: skill mention checks
    for skill_file in skill_files:
        skill_dir = skill_file.parent
        skill_name = skill_dir.name
        blueprint_file = skill_dir / "blueprint.yaml"

        text = skill_file.read_text(encoding="utf-8")

        try:
            raw_blueprint = yaml.safe_load(blueprint_file.read_text(encoding="utf-8")) or {}
        except (OSError, yaml.YAMLError):
            raw_blueprint = {}
        if isinstance(raw_blueprint, dict) and (
            raw_blueprint.get("schema_version") == 2 or "blueprint_type" in raw_blueprint
        ):
            try:
                graph = load_skill_blueprint_graph(skill_dir)
            except BlueprintGraphError:
                graph = None
            if graph is not None:
                errors.extend(_validate_typed_body_interfaces(graph, skill_name_set))

        # Check for deprecated markers
        for m in _DEPRECATED_MARKERS_RE.finditer(text):
            lineno = text[: m.start()].count("\n") + 1
            errors.append(
                f"{skill_file}:{lineno}: {m.group(0)} — "
                f"declare cross-skill use through blueprint.yaml `uses_interfaces`"
            )

        blueprint_uses = _load_blueprint_used_skills(blueprint_file) if blueprint_file.exists() else []

        # Extract exact skill-name mentions in body
        body = _strip_frontmatter_and_deps(text)
        other_skills = sorted(s for s in skill_names if s != skill_name)
        body_mentions = sorted(s for s in other_skills if _word_boundary_mentions(body, s))
        undeclared_mentions = sorted(set(body_mentions) - set(blueprint_uses))

        if undeclared_mentions:
            errors.append(
                f"{skill_file}: exact skill-name mentions in SKILL.md body are not declared "
                f"through {blueprint_file}:interfaces.*.*.uses_interfaces: {undeclared_mentions}"
            )

    return errors


def main() -> int:
    errors = validate(Path(__file__).resolve().parents[3])
    if errors:
        print("error: invalid skill dependencies.", file=sys.stderr)
        for error in errors:
            print(f"  {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
