from __future__ import annotations

import json
import os
import shutil
import subprocess
import tomllib
from dataclasses import replace
from pathlib import Path

import pytest

from officina.common import atomic_files
import officina.install.managed_runtime as managed_runtime
from officina.install.managed_runtime import (
    ManagedRuntimeError,
    _source_revision,
    _venv_python_bin,
    _venv_site_packages,
    build_candidate_release,
    declared_python_packages,
    optional_python_packages,
)
from test_support.git_repository import GitTestRepository
from test_support.uv_subprocess import FakeCompletedProcess, fake_uv_subprocess_run

REPO_ROOT = Path(__file__).resolve().parents[1]

REAL_MANIFEST = Path(__file__).resolve().parents[1] / "references" / "blueprint" / "runtime_dependencies.json"
UV_BIN = shutil.which("uv")
# A real Path's str() renders with the host's native separators regardless
# of the `platform=` string passed to build_candidate_release (that
# parameter only selects *logical* branching inside the function, e.g.
# venv layout -- it never changes how Python itself stringifies a Path
# object on this interpreter). So every assertion below must compare
# against str(FAKE_UV_BIN), not a hardcoded POSIX-style literal, to stay
# correct on a real Windows test host.
FAKE_UV_BIN = Path("/fake/uv")


def test_wheel_metadata_preserves_non_python_runtime_assets() -> None:
    with (REPO_ROOT / "pyproject.toml").open("rb") as stream:
        configuration = tomllib.load(stream)

    setuptools = configuration["tool"]["setuptools"]
    assert setuptools["package-data"]["officina"] == ["**/*"]
    assert set(setuptools["exclude-package-data"]["officina"]) == {
        "**/__pycache__/*",
        "**/*.pyc",
        "**/*.pyo",
    }


def test_source_revision_falls_back_to_packaged_source_fingerprint(
    monkeypatch,
    tmp_path,
):
    repo_root = tmp_path / "packaged-plugin"
    source_root = repo_root / "src" / "officina"
    source_root.mkdir(parents=True)
    (repo_root / "pyproject.toml").write_text("[project]\nname='example'\n")
    module = source_root / "runtime.py"
    module.write_text("VALUE = 1\n")

    monkeypatch.setattr(
        "subprocess.run",
        lambda *args, **kwargs: subprocess.CompletedProcess(
            args[0], 128, b"", b"fatal: not a git repository"
        ),
    )

    first = _source_revision(repo_root)
    assert len(first) == 40
    assert set(first) <= set("0123456789abcdef")
    assert _source_revision(repo_root) == first

    (repo_root / "README.md").write_text("not wheel input\n")
    assert _source_revision(repo_root) == first

    cache_file = source_root / "__pycache__" / "runtime.cpython-311.pyc"
    cache_file.parent.mkdir()
    cache_file.write_bytes(b"generated bytecode")
    assert _source_revision(repo_root) == first

    module.write_text("VALUE = 2\n")
    assert _source_revision(repo_root) != first


def test_release_source_digest_ignores_generated_bytecode_but_detects_source_tamper(
    tmp_path,
):
    installed_source = tmp_path / "officina"
    installed_source.mkdir()
    module = installed_source / "runtime.py"
    module.write_text("VALUE = 1\n")
    original = managed_runtime._directory_digest(installed_source)

    cache = installed_source / "__pycache__" / "runtime.cpython-311.pyc"
    cache.parent.mkdir()
    cache.write_bytes(b"interpreter-generated cache")
    assert managed_runtime._directory_digest(installed_source) == original

    module.write_text("VALUE = 2\n")
    assert managed_runtime._directory_digest(installed_source) != original


def test_source_revision_ignores_parent_repository_and_ambient_git_routing(
    monkeypatch,
    tmp_path,
):
    parent_repo = tmp_path / "unrelated-repository"
    git = GitTestRepository.create(parent_repo)
    (parent_repo / "tracked.txt").write_text("parent repository\n")
    git.git("add", "tracked.txt")
    git.git("commit", "--quiet", "-m", "initial")
    parent_revision = git.git("rev-parse", "HEAD").stdout.decode("ascii").strip()

    packaged_root = parent_repo / "plugin-copy"
    source_root = packaged_root / "src" / "officina"
    source_root.mkdir(parents=True)
    (packaged_root / "pyproject.toml").write_text("[project]\nname='example'\n")
    module = source_root / "runtime.py"
    module.write_text("VALUE = 1\n")

    ambient = GitTestRepository.create(tmp_path / "ambient-repository")
    (ambient.root / "tracked.txt").write_text("ambient repository\n")
    ambient.git("add", "tracked.txt")
    ambient.git("commit", "--quiet", "-m", "ambient")
    monkeypatch.setenv("GIT_DIR", str(ambient.root / ".git"))
    monkeypatch.setenv("GIT_WORK_TREE", str(packaged_root))

    first = _source_revision(packaged_root)
    assert first != parent_revision
    module.write_text("VALUE = 2\n")
    assert _source_revision(packaged_root) != first


@pytest.mark.parametrize(
    "relative_symlink",
    (Path("linked.py"), Path("__pycache__") / "linked.pyc"),
)
def test_packaged_source_revision_rejects_symlinks_even_in_bytecode_paths(
    monkeypatch,
    tmp_path,
    relative_symlink,
):
    repo_root = tmp_path / "packaged-plugin"
    source_root = repo_root / "src" / "officina"
    source_root.mkdir(parents=True)
    (repo_root / "pyproject.toml").write_text("[project]\nname='example'\n")
    (source_root / "runtime.py").write_text("VALUE = 1\n")
    target = tmp_path / "outside.py"
    target.write_text("outside\n")
    link = source_root / relative_symlink
    link.parent.mkdir(parents=True, exist_ok=True)
    try:
        link.symlink_to(target)
    except OSError as exc:
        # famulus-skip: category=platform-contract; reason=some Windows runners deny symlink creation; alternate=Linux and macOS exercise both ordinary and bytecode-path symlink rejection
        pytest.skip(f"symlink creation is unavailable: {exc}")
    monkeypatch.setattr(
        "subprocess.run",
        lambda *args, **kwargs: subprocess.CompletedProcess(
            args[0], 128, b"", b"fatal: not a git repository"
        ),
    )

    with pytest.raises(ManagedRuntimeError, match="symlink is forbidden"):
        _source_revision(repo_root)


def test_declared_python_packages_matches_today_baseline():
    packages = declared_python_packages(REAL_MANIFEST, platform="linux")
    assert packages == (
        "bibtexparser",
        "cryptography>=44.0.1",
        "dateparser",
        "jsonschema>=4",
        "keyring==25.6.0",
        "marker-pdf",
        "PyYAML>=6",
        "rich",
    )


def test_declared_python_packages_filters_by_platform(tmp_path):
    manifest = tmp_path / "runtime_dependencies.json"
    manifest.write_text(json.dumps({
        "version": 1,
        "skills": {
            "example": {
                "interfaces": {
                    "run": {
                        "dependencies": [
                            {"kind": "python-package", "name": "pywin32", "version": "1.0", "platforms": {"windows": True}},
                            {"kind": "python-package", "name": "pyyaml", "version": "6.0", "platforms": {"linux": True, "macos": True, "windows": True}},
                        ]
                    }
                }
            }
        },
    }))
    assert declared_python_packages(manifest, platform="linux") == ("pyyaml==6.0",)


def test_declared_python_packages_rejects_unsupported_schema_version(tmp_path):
    manifest = tmp_path / "runtime_dependencies.json"
    manifest.write_text(json.dumps({"version": 3, "skills": {}}))
    with pytest.raises(ManagedRuntimeError):
        declared_python_packages(manifest, platform="linux")


def test_declared_python_packages_include_optional_false_excludes_marker_pdf():
    """marker-pdf pulls in the full torch/transformers/CUDA stack (several
    GB) for pdf-to-markdown's OCR models alone -- the "core" set (what a
    fresh install gets by default) excludes it; every other real declared
    package stays."""
    core = declared_python_packages(REAL_MANIFEST, platform="linux", include_optional=False)
    assert "marker-pdf" not in core
    assert core == (
        "bibtexparser",
        "cryptography>=44.0.1",
        "dateparser",
        "jsonschema>=4",
        "keyring==25.6.0",
        "PyYAML>=6",
        "rich",
    )


def test_declared_python_packages_include_optional_true_is_the_default():
    assert declared_python_packages(REAL_MANIFEST, platform="linux") == declared_python_packages(
        REAL_MANIFEST, platform="linux", include_optional=True
    )


def test_optional_python_packages_returns_just_the_deferred_set():
    assert optional_python_packages(REAL_MANIFEST, platform="linux") == ("marker-pdf",)


def test_venv_python_bin_posix_is_bin_python():
    venv_dir = Path("/fake/release/venv")
    for platform_name in ("linux", "macos"):
        assert _venv_python_bin(venv_dir, platform=platform_name) == venv_dir / "bin" / "python"


def test_venv_python_bin_windows_is_scripts_python_exe():
    venv_dir = Path("/fake/release/venv")
    assert _venv_python_bin(venv_dir, platform="windows") == venv_dir / "Scripts" / "python.exe"


def test_build_candidate_release_on_windows_uses_scripts_python_exe(monkeypatch, tmp_path):
    """Regression test for a real bug: build_candidate_release used to
    hardcode `venv_dir / "bin" / "python"` with no platform branch, so on
    Windows (where `uv venv` creates `Scripts\\python.exe`) python_bin never
    existed. That made runtime_pointer.activate_release raise
    RuntimePointerError -- not a ManagedRuntimeError -- which
    _phase_entry.py's `except ManagedRuntimeError` didn't catch, crashing
    the installer. This exercises build_candidate_release with
    platform="windows" against a fake uv that lays out the venv the real
    Windows uv would, and asserts the batch pip-install call and the
    activated pointer both use the Windows interpreter path.
    """
    calls: list = []
    monkeypatch.setattr(
        "subprocess.run",
        fake_uv_subprocess_run(calls, trusted_python_dir=tmp_path / "uv-python-store", windows=True),
    )

    pointer = build_candidate_release(
        runtime_root=tmp_path / "runtime",
        manifest_path=REAL_MANIFEST,
        platform="windows",
        uv_bin=FAKE_UV_BIN,
        python_version="3.11",
    )

    assert pointer.python_bin == pointer.runtime_source / "venv" / "Scripts" / "python.exe"
    assert pointer.python_bin.exists()
    pip_call = calls[1]
    assert pip_call[:4] == [str(FAKE_UV_BIN), "pip", "install", "--python"]
    assert pip_call[4] == str(pointer.python_bin)


def test_build_candidate_release_creates_venv_then_one_batch_pip_install(monkeypatch, tmp_path):
    calls: list = []
    monkeypatch.setattr(
        "subprocess.run", fake_uv_subprocess_run(calls, trusted_python_dir=tmp_path / "uv-python-store")
    )

    pointer = build_candidate_release(
        runtime_root=tmp_path / "runtime",
        manifest_path=REAL_MANIFEST,
        platform="linux",
        uv_bin=FAKE_UV_BIN,
        python_version="3.11",
    )

    assert len(calls) == 7
    venv_call, pip_call, *probe_and_trust_calls = calls
    python_dir_call = probe_and_trust_calls[2]
    assert venv_call == [str(FAKE_UV_BIN), "venv", "--python", "3.11", str(pointer.runtime_source / "venv")]
    assert pip_call[:4] == [str(FAKE_UV_BIN), "pip", "install", "--python"]
    assert pip_call[4] == str(pointer.python_bin)
    assert "setuptools==80.9.0" in pip_call
    assert "PyYAML==6.0.2" in pip_call
    assert python_dir_call == [str(FAKE_UV_BIN), "python", "dir"]
    assert pointer.python_bin.exists()


def test_build_candidate_release_include_optional_dependencies_false_excludes_marker_pdf(monkeypatch, tmp_path):
    calls: list = []
    monkeypatch.setattr(
        "subprocess.run", fake_uv_subprocess_run(calls, trusted_python_dir=tmp_path / "uv-python-store")
    )

    build_candidate_release(
        runtime_root=tmp_path / "runtime",
        manifest_path=REAL_MANIFEST,
        platform="linux",
        uv_bin=FAKE_UV_BIN,
        python_version="3.11",
        include_optional_dependencies=False,
    )

    pip_call = calls[1]
    assert "marker-pdf" not in pip_call
    assert "bibtexparser" in pip_call  # a core (non-optional) package is still requested


def test_build_candidate_release_provisions_venv_before_installing_packages(monkeypatch, tmp_path):
    """Dedicated sanity check for the uv-venv step's exact arguments and
    ordering, independent of the batch-install call-count assertion above."""
    calls: list = []
    monkeypatch.setattr(
        "subprocess.run", fake_uv_subprocess_run(calls, trusted_python_dir=tmp_path / "uv-python-store")
    )

    build_candidate_release(
        runtime_root=tmp_path / "runtime",
        manifest_path=REAL_MANIFEST,
        platform="linux",
        uv_bin=FAKE_UV_BIN,
        python_version="3.11",
    )

    assert calls[0][:4] == [str(FAKE_UV_BIN), "venv", "--python", "3.11"]
    assert calls[1][0] == str(FAKE_UV_BIN)


def _prepare_repo_candidate(monkeypatch, tmp_path):
    calls: list[list[str]] = []
    monkeypatch.setattr(
        "subprocess.run",
        fake_uv_subprocess_run(calls, trusted_python_dir=tmp_path / "uv-python-store"),
    )
    prepared = managed_runtime.prepare_candidate_release(
        runtime_root=tmp_path / "runtime",
        manifest_path=REAL_MANIFEST,
        platform="linux",
        uv_bin=FAKE_UV_BIN,
        python_version="3.11",
        repo_root=REPO_ROOT,
        include_optional_dependencies=False,
    )
    return prepared, calls


def test_prepare_candidate_release_builds_validated_release_without_writing_pointer(
    monkeypatch, tmp_path
):
    prepared, _calls = _prepare_repo_candidate(monkeypatch, tmp_path)

    assert prepared.python_bin.exists()
    assert prepared.release_dir.name == prepared.release_id
    assert prepared.repository_config == (REPO_ROOT / "officina.toml").resolve()
    assert len(prepared.resolver_bundle_id) == 64
    assert not (tmp_path / "runtime" / "current.json").exists()


@pytest.mark.parametrize(
    "boundary",
    (
        "directory-created",
        "venv-created",
        "dependencies-installed",
        "wheel-built",
        "probe-completed",
        "artifact-written",
        "bundle-published",
    ),
)
def test_prepare_failure_removes_only_the_exact_new_candidate(
    monkeypatch, tmp_path, boundary
):
    runtime_root = tmp_path / "runtime"
    releases_root = runtime_root / "releases"
    older = releases_root / "older-known-good"
    older.mkdir(parents=True)
    sentinel = older / "sentinel"
    sentinel.write_text("preserve me\n")
    monkeypatch.setattr(
        managed_runtime,
        "_new_release_id",
        lambda: "2026-08-12T00-00-00Z-c0ffee",
    )
    calls: list[list[str]] = []
    monkeypatch.setattr(
        "subprocess.run",
        fake_uv_subprocess_run(calls, trusted_python_dir=tmp_path / "uv-python-store"),
    )

    def fail(message):
        def raising(*args, **kwargs):
            raise ManagedRuntimeError(message)

        return raising

    if boundary == "directory-created":
        monkeypatch.setattr(managed_runtime, "_create_release_venv", fail(boundary))
    elif boundary == "venv-created":
        monkeypatch.setattr(managed_runtime, "_run_dependency_install", fail(boundary))
    elif boundary == "dependencies-installed":
        monkeypatch.setattr(managed_runtime, "_build_officina_wheel", fail(boundary))
    elif boundary == "wheel-built":
        real_install = managed_runtime._run_dependency_install
        install_count = 0

        def fail_second_install(**kwargs):
            nonlocal install_count
            install_count += 1
            if install_count == 2:
                raise ManagedRuntimeError(boundary)
            return real_install(**kwargs)

        monkeypatch.setattr(managed_runtime, "_run_dependency_install", fail_second_install)
    elif boundary == "probe-completed":
        real_replace = atomic_files.atomic_replace_bytes

        def fail_artifact(path, *args, **kwargs):
            if Path(path).name == "artifact.json":
                raise OSError(boundary)
            return real_replace(path, *args, **kwargs)

        monkeypatch.setattr(managed_runtime.atomic_files, "atomic_replace_bytes", fail_artifact)
    elif boundary == "artifact-written":
        monkeypatch.setattr(managed_runtime, "_uv_python_install_dir", fail(boundary))
    else:
        real_validate = managed_runtime._validate_resolver_bundle

        def fail_after_publish(*args, **kwargs):
            real_validate(*args, **kwargs)
            raise ManagedRuntimeError(boundary)

        monkeypatch.setattr(managed_runtime, "_validate_resolver_bundle", fail_after_publish)

    with pytest.raises((ManagedRuntimeError, OSError), match=boundary):
        managed_runtime.prepare_candidate_release(
            runtime_root=runtime_root,
            manifest_path=REAL_MANIFEST,
            platform="linux",
            uv_bin=FAKE_UV_BIN,
            python_version="3.11",
            repo_root=REPO_ROOT,
            include_optional_dependencies=False,
        )

    assert sentinel.read_text() == "preserve me\n"
    assert sorted(path.name for path in releases_root.iterdir()) == ["older-known-good"]
    assert not (runtime_root / "current.json").exists()


def test_prepare_release_id_collision_never_removes_existing_release(monkeypatch, tmp_path):
    runtime_root = tmp_path / "runtime"
    release_id = "2026-08-12T00-00-00Z-c0ffee"
    existing = runtime_root / "releases" / release_id
    existing.mkdir(parents=True)
    sentinel = existing / "sentinel"
    sentinel.write_text("existing release\n")
    monkeypatch.setattr(managed_runtime, "_new_release_id", lambda: release_id)

    with pytest.raises(FileExistsError):
        managed_runtime.prepare_candidate_release(
            runtime_root=runtime_root,
            manifest_path=REAL_MANIFEST,
            platform="linux",
            uv_bin=FAKE_UV_BIN,
            python_version="3.11",
            repo_root=REPO_ROOT,
            include_optional_dependencies=False,
        )

    assert sentinel.read_text() == "existing release\n"


def test_activate_prepared_release_writes_v3_pointer_selecting_published_bundle(
    monkeypatch, tmp_path
):
    prepared, _calls = _prepare_repo_candidate(monkeypatch, tmp_path)

    pointer = managed_runtime.activate_prepared_release(tmp_path / "runtime", prepared)
    payload = json.loads((tmp_path / "runtime" / "current.json").read_text())

    assert pointer.resolver_bundle_id == prepared.resolver_bundle_id
    assert payload["schema_version"] == 3
    assert payload["resolver_bundle_id"] == prepared.resolver_bundle_id
    bundle = tmp_path / "runtime" / "resolvers" / "bundles" / prepared.resolver_bundle_id
    manifest_bytes = (bundle / "manifest.json").read_bytes()
    assert __import__("hashlib").sha256(manifest_bytes).hexdigest() == prepared.resolver_bundle_id


def test_activation_revalidates_bundle_and_preserves_prior_pointer_on_tamper(
    monkeypatch, tmp_path
):
    prepared, _calls = _prepare_repo_candidate(monkeypatch, tmp_path)
    runtime_root = tmp_path / "runtime"
    prior_release = runtime_root / "releases" / "prior"
    prior_python = prior_release / "venv" / "bin" / "python"
    prior_python.parent.mkdir(parents=True)
    prior_python.write_text("#!/bin/sh\n")
    from officina.install.runtime_pointer import activate_release

    activate_release(
        runtime_root=runtime_root,
        release_dir=prior_release,
        python_bin=prior_python,
        trusted_interpreter_roots=prepared.trusted_interpreter_roots,
        repository_config=prepared.repository_config,
        resolver_bundle_id=prepared.resolver_bundle_id,
    )
    prior_bytes = (runtime_root / "current.json").read_bytes()
    bundle_launch = (
        runtime_root
        / "resolvers"
        / "bundles"
        / prepared.resolver_bundle_id
        / "launch.py"
    )
    bundle_launch.chmod(0o755)
    bundle_launch.write_text("tampered\n")

    with pytest.raises(ManagedRuntimeError, match="resolver bundle"):
        managed_runtime.activate_prepared_release(runtime_root, prepared)

    assert (runtime_root / "current.json").read_bytes() == prior_bytes


def test_activation_requires_artifact_metadata_and_reprobes_candidate(monkeypatch, tmp_path):
    prepared, _calls = _prepare_repo_candidate(monkeypatch, tmp_path)
    runtime_root = tmp_path / "runtime"
    (prepared.release_dir / "artifact.json").unlink()
    probe_calls = []
    monkeypatch.setattr(
        managed_runtime,
        "_validate_candidate_runtime",
        lambda **kwargs: probe_calls.append(kwargs),
    )

    with pytest.raises(ManagedRuntimeError, match="artifact"):
        managed_runtime.activate_prepared_release(runtime_root, prepared)

    assert probe_calls == []
    assert not (runtime_root / "current.json").exists()


def test_activation_reprobes_even_a_previously_validated_candidate(monkeypatch, tmp_path):
    prepared, _calls = _prepare_repo_candidate(monkeypatch, tmp_path)
    monkeypatch.setattr(
        managed_runtime,
        "_validate_candidate_runtime",
        lambda **kwargs: (_ for _ in ()).throw(ManagedRuntimeError("reprobe failed")),
    )

    with pytest.raises(ManagedRuntimeError, match="reprobe failed"):
        managed_runtime.activate_prepared_release(tmp_path / "runtime", prepared)

    assert not (tmp_path / "runtime" / "current.json").exists()


def test_activation_rejects_release_symlink_and_mismatched_identity(monkeypatch, tmp_path):
    prepared, _calls = _prepare_repo_candidate(monkeypatch, tmp_path)
    runtime_root = tmp_path / "runtime"
    alias = runtime_root / "releases" / "2026-08-12T00-00-00Z-badbad"
    try:
        alias.symlink_to(prepared.release_dir, target_is_directory=True)
    except OSError as exc:
        # famulus-skip: category=platform-contract; reason=some Windows runners deny directory-symlink creation; alternate=Linux and macOS exercise exact release-symlink rejection
        pytest.skip(f"symlink creation is unavailable: {exc}")

    with pytest.raises(ManagedRuntimeError, match="symlink|identity|immediate"):
        managed_runtime.activate_prepared_release(
            runtime_root,
            replace(prepared, release_id=alias.name, release_dir=alias),
        )

    assert not (runtime_root / "current.json").exists()


def test_activation_rejects_python_entry_from_another_release(monkeypatch, tmp_path):
    prepared, _calls = _prepare_repo_candidate(monkeypatch, tmp_path)
    runtime_root = tmp_path / "runtime"
    other_python = runtime_root / "releases" / "other" / "venv" / "bin" / "python"
    other_python.parent.mkdir(parents=True)
    other_python.write_text("#!/bin/sh\n")

    with pytest.raises(ManagedRuntimeError, match="python_bin|interpreter"):
        managed_runtime.activate_prepared_release(
            runtime_root,
            replace(prepared, python_bin=other_python),
        )

    assert not (runtime_root / "current.json").exists()


def test_activation_requires_prepared_trust_to_equal_bundle_sidecar(monkeypatch, tmp_path):
    prepared, _calls = _prepare_repo_candidate(monkeypatch, tmp_path)

    with pytest.raises(ManagedRuntimeError, match="trust"):
        managed_runtime.activate_prepared_release(
            tmp_path / "runtime",
            replace(prepared, trusted_interpreter_roots=(tmp_path / "forged-trust",)),
        )

    assert not (tmp_path / "runtime" / "current.json").exists()


def test_pointer_validation_failure_preserves_prior_pointer_and_candidate(
    monkeypatch, tmp_path
):
    prepared, _calls = _prepare_repo_candidate(monkeypatch, tmp_path)
    runtime_root = tmp_path / "runtime"
    prior_release = runtime_root / "releases" / "prior"
    prior_python = prior_release / "venv" / "bin" / "python"
    prior_python.parent.mkdir(parents=True)
    prior_python.write_text("#!/bin/sh\n")
    from officina.install.runtime_pointer import activate_release

    activate_release(
        runtime_root=runtime_root,
        release_dir=prior_release,
        python_bin=prior_python,
        trusted_interpreter_roots=prepared.trusted_interpreter_roots,
        repository_config=prepared.repository_config,
        resolver_bundle_id=prepared.resolver_bundle_id,
    )
    prior_bytes = (runtime_root / "current.json").read_bytes()

    with pytest.raises(ManagedRuntimeError, match="pointer validation"):
        managed_runtime.activate_prepared_release(
            runtime_root,
            replace(prepared, repository_config=tmp_path / "missing" / "officina.toml"),
        )

    assert (runtime_root / "current.json").read_bytes() == prior_bytes
    assert prepared.release_dir.is_dir()


def test_pointer_replace_failure_preserves_prior_pointer_and_candidate(monkeypatch, tmp_path):
    prepared, _calls = _prepare_repo_candidate(monkeypatch, tmp_path)
    runtime_root = tmp_path / "runtime"
    prior_release = runtime_root / "releases" / "prior"
    prior_python = prior_release / "venv" / "bin" / "python"
    prior_python.parent.mkdir(parents=True)
    prior_python.write_text("#!/bin/sh\n")
    from officina.install.runtime_pointer import activate_release

    activate_release(
        runtime_root=runtime_root,
        release_dir=prior_release,
        python_bin=prior_python,
        trusted_interpreter_roots=prepared.trusted_interpreter_roots,
        repository_config=prepared.repository_config,
        resolver_bundle_id=prepared.resolver_bundle_id,
    )
    prior_bytes = (runtime_root / "current.json").read_bytes()
    monkeypatch.setattr(
        "officina.install.runtime_pointer.atomic_replace_bytes",
        lambda *args, **kwargs: (_ for _ in ()).throw(OSError("pointer-replace")),
    )

    with pytest.raises(OSError, match="pointer-replace"):
        managed_runtime.activate_prepared_release(runtime_root, prepared)

    assert (runtime_root / "current.json").read_bytes() == prior_bytes
    assert prepared.release_dir.is_dir()


def test_failure_after_pointer_replace_keeps_new_pointer_for_journal_recovery(
    monkeypatch, tmp_path
):
    prepared, _calls = _prepare_repo_candidate(monkeypatch, tmp_path)
    runtime_root = tmp_path / "runtime"
    from officina.install import runtime_pointer

    real_replace = runtime_pointer.atomic_replace_bytes

    def replace_then_report_uncertain(*args, **kwargs):
        real_replace(*args, **kwargs)
        raise OSError("journal-before-advance")

    monkeypatch.setattr(runtime_pointer, "atomic_replace_bytes", replace_then_report_uncertain)

    with pytest.raises(OSError, match="journal-before-advance"):
        managed_runtime.activate_prepared_release(runtime_root, prepared)

    payload = json.loads((runtime_root / "current.json").read_text())
    assert payload["release_id"] == prepared.release_id
    assert payload["resolver_bundle_id"] == prepared.resolver_bundle_id
    assert prepared.release_dir.is_dir()


def test_pruning_is_explicit_and_retains_current_plus_one_previous(monkeypatch, tmp_path):
    runtime_root = tmp_path / "runtime"
    calls: list = []
    releases = [
        _prepare_and_activate_named(
            monkeypatch,
            tmp_path,
            runtime_root,
            release_id,
            calls,
        )
        for release_id in (
            "2026-01-01T00-00-00Z-aaaaaa",
            "2026-01-02T00-00-00Z-bbbbbb",
            "2026-01-03T00-00-00Z-cccccc",
        )
    ]

    assert len(tuple((runtime_root / "releases").iterdir())) == 3
    removed = managed_runtime.prune_old_releases(runtime_root)

    assert tuple(path.name for path in removed) == ("2026-01-01T00-00-00Z-aaaaaa",)
    assert sorted(path.name for path in (runtime_root / "releases").iterdir()) == sorted(
        (releases[1].release_id, releases[2].release_id)
    )


def _prepare_and_activate_named(monkeypatch, tmp_path, runtime_root, release_id, calls):
    monkeypatch.setattr(managed_runtime, "_new_release_id", lambda: release_id)
    monkeypatch.setattr(
        "subprocess.run",
        fake_uv_subprocess_run(calls, trusted_python_dir=tmp_path / "uv-python-store"),
    )
    prepared = managed_runtime.prepare_candidate_release(
        runtime_root=runtime_root,
        manifest_path=REAL_MANIFEST,
        platform="linux",
        uv_bin=FAKE_UV_BIN,
        python_version="3.11",
        repo_root=REPO_ROOT,
        include_optional_dependencies=False,
    )
    managed_runtime.activate_prepared_release(runtime_root, prepared)
    return prepared


def test_pruning_uses_durable_activation_order_not_random_release_suffix(
    monkeypatch, tmp_path
):
    runtime_root = tmp_path / "runtime"
    calls = []
    first = _prepare_and_activate_named(
        monkeypatch, tmp_path, runtime_root, "2026-08-12T00-00-00Z-ffffff", calls
    )
    second = _prepare_and_activate_named(
        monkeypatch, tmp_path, runtime_root, "2026-08-12T00-00-00Z-000000", calls
    )
    current = _prepare_and_activate_named(
        monkeypatch, tmp_path, runtime_root, "2026-08-12T00-00-00Z-aaaaaa", calls
    )

    removed = managed_runtime.prune_old_releases(runtime_root)

    assert tuple(path.name for path in removed) == (first.release_id,)
    assert second.release_dir.is_dir()
    assert current.release_dir.is_dir()


def test_pruning_ignores_regex_shaped_sentinel_and_tampered_candidate(
    monkeypatch, tmp_path
):
    runtime_root = tmp_path / "runtime"
    calls = []
    first = _prepare_and_activate_named(
        monkeypatch, tmp_path, runtime_root, "2026-08-12T00-00-00Z-111111", calls
    )
    current = _prepare_and_activate_named(
        monkeypatch, tmp_path, runtime_root, "2026-08-12T00-00-00Z-222222", calls
    )
    sentinel = runtime_root / "releases" / "2026-08-12T00-00-00Z-000000"
    sentinel.mkdir()
    (sentinel / "sentinel").write_text("user state\n")
    tampered = runtime_root / "releases" / "2026-08-12T00-00-00Z-101010"
    shutil.copytree(first.release_dir, tampered)
    (tampered / "artifact.json").write_text("{}")

    assert managed_runtime.prune_old_releases(runtime_root) == ()
    assert sentinel.is_dir()
    assert tampered.is_dir()
    assert first.release_dir.is_dir()
    assert current.release_dir.is_dir()


def test_pruning_ignores_metadata_bearing_malformed_name_without_partial_deletion(
    monkeypatch, tmp_path
):
    runtime_root = tmp_path / "runtime"
    calls = []
    first = _prepare_and_activate_named(
        monkeypatch, tmp_path, runtime_root, "2026-08-12T00-00-00Z-111111", calls
    )
    previous = _prepare_and_activate_named(
        monkeypatch, tmp_path, runtime_root, "2026-08-12T00-00-00Z-222222", calls
    )
    current = _prepare_and_activate_named(
        monkeypatch, tmp_path, runtime_root, "2026-08-12T00-00-00Z-333333", calls
    )
    malformed = runtime_root / "releases" / "metadata-bearing-third-state"
    shutil.copytree(first.release_dir, malformed)

    ordered = (
        (first.release_dir, 10),
        (malformed, 20),
        (previous.release_dir, 30),
        (current.release_dir, 40),
    )
    for release_dir, activated_at_ns in ordered:
        artifact_path = release_dir / "artifact.json"
        artifact = json.loads(artifact_path.read_text())
        artifact["release_id"] = release_dir.name
        artifact_path.write_text(json.dumps(artifact))
        activation_path = release_dir / "activation.json"
        activation = json.loads(activation_path.read_text())
        activation["release_id"] = release_dir.name
        activation["activated_at_ns"] = activated_at_ns
        activation_path.write_text(json.dumps(activation))

    removed = managed_runtime.prune_old_releases(runtime_root)

    assert tuple(path.name for path in removed) == (first.release_id,)
    assert not first.release_dir.exists()
    assert malformed.is_dir()
    assert previous.release_dir.is_dir()
    assert current.release_dir.is_dir()


def test_pruning_rejects_malformed_current_identity_without_removing_anything(
    monkeypatch, tmp_path
):
    runtime_root = tmp_path / "runtime"
    calls = []
    first = _prepare_and_activate_named(
        monkeypatch, tmp_path, runtime_root, "2026-08-12T00-00-00Z-111111", calls
    )
    current = _prepare_and_activate_named(
        monkeypatch, tmp_path, runtime_root, "2026-08-12T00-00-00Z-222222", calls
    )
    payload = json.loads((runtime_root / "current.json").read_text())
    payload["release_id"] = first.release_id
    (runtime_root / "current.json").write_text(json.dumps(payload))

    with pytest.raises(ManagedRuntimeError, match="release_id"):
        managed_runtime.prune_old_releases(runtime_root)

    assert first.release_dir.is_dir()
    assert current.release_dir.is_dir()


@pytest.mark.parametrize("tamper", ("missing", "negative-time"))
def test_pruning_requires_valid_activation_metadata_for_current_release(
    monkeypatch, tmp_path, tamper
):
    runtime_root = tmp_path / "runtime"
    calls = []
    releases = [
        _prepare_and_activate_named(
            monkeypatch,
            tmp_path,
            runtime_root,
            release_id,
            calls,
        )
        for release_id in (
            "2026-08-12T00-00-00Z-111111",
            "2026-08-12T00-00-00Z-222222",
            "2026-08-12T00-00-00Z-333333",
        )
    ]
    activation_path = releases[-1].release_dir / "activation.json"
    if tamper == "missing":
        activation_path.unlink()
    else:
        activation = json.loads(activation_path.read_text())
        activation["activated_at_ns"] = -1
        activation_path.write_text(json.dumps(activation))

    with pytest.raises(ManagedRuntimeError, match="current.*activation"):
        managed_runtime.prune_old_releases(runtime_root)

    assert all(release.release_dir.is_dir() for release in releases)


def test_release_hierarchy_is_fsynced_before_pointer_replace(monkeypatch, tmp_path):
    events = []
    real_fsync = managed_runtime._fsync_directory
    real_replace = __import__(
        "officina.install.runtime_pointer", fromlist=["atomic_replace_bytes"]
    ).atomic_replace_bytes

    def record_fsync(path):
        events.append(("fsync", Path(path)))
        return real_fsync(path)

    def record_pointer(path, *args, **kwargs):
        events.append(("pointer", Path(path)))
        return real_replace(path, *args, **kwargs)

    monkeypatch.setattr(managed_runtime, "_fsync_directory", record_fsync)
    prepared, _calls = _prepare_repo_candidate(monkeypatch, tmp_path)
    monkeypatch.setattr(
        "officina.install.runtime_pointer.atomic_replace_bytes", record_pointer
    )
    managed_runtime.activate_prepared_release(tmp_path / "runtime", prepared)

    pointer_index = next(i for i, event in enumerate(events) if event[0] == "pointer")
    assert ("fsync", prepared.release_dir) in events[:pointer_index]
    assert ("fsync", prepared.release_dir.parent) in events[:pointer_index]


def test_build_candidate_release_failure_writes_no_pointer(monkeypatch, tmp_path):
    def fail(*a, **k):
        raise ManagedRuntimeError("simulated failure")

    monkeypatch.setattr("officina.install.managed_runtime._run_dependency_install", fail)
    monkeypatch.setattr(
        "officina.install.managed_runtime._create_release_venv",
        lambda **kwargs: None,
    )
    runtime_root = tmp_path / "runtime"
    with pytest.raises(ManagedRuntimeError):
        build_candidate_release(
            runtime_root=runtime_root,
            manifest_path=REAL_MANIFEST,
            platform="linux",
            uv_bin=FAKE_UV_BIN,
            python_version="3.11",
        )
    assert not (runtime_root / "current.json").exists()


def test_build_candidate_release_venv_failure_writes_no_pointer(monkeypatch, tmp_path):
    def fail(**kwargs):
        raise ManagedRuntimeError("simulated venv creation failure")

    monkeypatch.setattr("officina.install.managed_runtime._create_release_venv", fail)
    runtime_root = tmp_path / "runtime"
    with pytest.raises(ManagedRuntimeError):
        build_candidate_release(
            runtime_root=runtime_root,
            manifest_path=REAL_MANIFEST,
            platform="linux",
            uv_bin=FAKE_UV_BIN,
            python_version="3.11",
        )
    assert not (runtime_root / "current.json").exists()


def test_build_candidate_release_resolver_deploy_failure_writes_no_pointer(monkeypatch, tmp_path):
    """A failed resolver deployment (e.g. disk full, permissions, a
    concurrent-install race) must behave exactly like every other
    build_candidate_release failure: no release is activated (current.json
    stays untouched) and the raised exception is a typed ManagedRuntimeError
    the installer's `except ManagedRuntimeError` can catch cleanly -- not a
    raw OSError propagating as an unhandled crash. This also guards against
    regressing back to deploying the resolver *after* activate_release,
    which would let a deployment failure leave a release activated with a
    missing/broken resolver.
    """
    calls: list = []
    monkeypatch.setattr(
        "subprocess.run", fake_uv_subprocess_run(calls, trusted_python_dir=tmp_path / "uv-python-store")
    )
    runtime_root = tmp_path / "runtime"
    resolver_path = runtime_root / "bootstrap" / "resolvers" / "v1" / "launch.py"
    real_atomic_replace_bytes = atomic_files.atomic_replace_bytes

    def fail_resolver_deploy(*args, **kwargs):
        if args[0] == resolver_path:
            raise OSError("simulated disk full")
        return real_atomic_replace_bytes(*args, **kwargs)

    monkeypatch.setattr(
        "officina.install.managed_runtime.atomic_files.atomic_replace_bytes",
        fail_resolver_deploy,
    )

    with pytest.raises(ManagedRuntimeError):
        build_candidate_release(
            runtime_root=runtime_root,
            manifest_path=REAL_MANIFEST,
            platform="linux",
            uv_bin=FAKE_UV_BIN,
            python_version="3.11",
        )

    assert not (runtime_root / "current.json").exists()
    # activate_release must never have run either: no release directory was
    # promoted, so no bootstrap/resolvers path exists beyond what
    # _deploy_resolver itself half-created before failing.
    assert not (runtime_root / "bootstrap" / "resolvers" / "v1" / "launch.py").exists()


def test_deploy_resolver_writes_through_atomic_replace_bytes_not_plain_copy(monkeypatch, tmp_path):
    """Regression test for a real bug: _deploy_resolver used to write the
    resolver with plain `shutil.copy2`, which is not atomic. The resolver
    at `<runtime_root>/bootstrap/resolvers/v1/launch.py` is a fixed path
    every generated launcher shim and every scheduled recurring-tasks job
    execs into, and build_candidate_release genuinely runs a second time
    against the same runtime_root during a normal install-then-update flow
    -- a non-atomic overwrite risks a torn read by a job executing the file
    at that exact moment. This asserts the real deployment goes through
    officina.common.atomic_files.atomic_replace_bytes (like its sibling
    uv_bootstrap.py/runtime_pointer.py writes) instead of shutil.copy2, and
    that the deployed file is both correct and executable.
    """
    calls: list = []
    monkeypatch.setattr(
        "subprocess.run", fake_uv_subprocess_run(calls, trusted_python_dir=tmp_path / "uv-python-store")
    )
    atomic_calls: list = []
    real_atomic_replace_bytes = atomic_files.atomic_replace_bytes

    def spying_atomic_replace_bytes(*args, **kwargs):
        atomic_calls.append((args, kwargs))
        return real_atomic_replace_bytes(*args, **kwargs)

    monkeypatch.setattr(
        "officina.install.managed_runtime.atomic_files.atomic_replace_bytes",
        spying_atomic_replace_bytes,
    )
    runtime_root = tmp_path / "runtime"

    build_candidate_release(
        runtime_root=runtime_root,
        manifest_path=REAL_MANIFEST,
        platform="linux",
        uv_bin=FAKE_UV_BIN,
        python_version="3.11",
    )

    resolver_path = runtime_root / "bootstrap" / "resolvers" / "v1" / "launch.py"
    resolver_calls = [call for call in atomic_calls if call[0][0] == resolver_path]
    assert len(resolver_calls) == 1
    args, kwargs = resolver_calls[0]
    assert args[0] == resolver_path
    assert kwargs["mode"] == 0o755
    assert resolver_path.exists()
    assert resolver_path.read_bytes() == (
        Path(__file__).resolve().parents[1]
        / "src" / "officina" / "install" / "resolvers" / "launch.py"
    ).read_bytes()
    assert os.access(resolver_path, os.X_OK)


def test_repo_candidate_installs_verified_officina_wheel_before_activation(monkeypatch, tmp_path):
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    (repo_root / "skills").mkdir()
    (repo_root / "src" / "officina").mkdir(parents=True)
    (repo_root / "officina.toml").write_text(
        'schema_version = 1\n[modules]\nroots = ["skills", "src/officina"]\n',
        encoding="utf-8",
    )
    manifest = repo_root / "runtime_dependencies.json"
    manifest.write_text('{"version": 2, "skills": {}}', encoding="utf-8")
    calls: list = []
    call_kwargs: list[dict] = []
    fake_run = fake_uv_subprocess_run(
        calls, trusted_python_dir=tmp_path / "uv-python-store"
    )

    def recording_run(cmd, **kwargs):
        call_kwargs.append(dict(kwargs))
        return fake_run(cmd, **kwargs)

    monkeypatch.setattr("subprocess.run", recording_run)
    runtime_root = tmp_path / "runtime"

    pointer = build_candidate_release(
        runtime_root=runtime_root,
        manifest_path=manifest,
        platform="linux",
        uv_bin=FAKE_UV_BIN,
        python_version="3.11",
        repo_root=repo_root,
    )

    build_index = next(i for i, call in enumerate(calls) if call[1] == "build")
    install_indices = [i for i, call in enumerate(calls) if call[1:3] == ["pip", "install"]]
    probe_indices = [i for i, call in enumerate(calls) if len(call) > 1 and call[1] == "-I"]
    assert install_indices[0] < build_index < install_indices[1] < min(probe_indices)
    assert "PyYAML==6.0.2" in calls[install_indices[0]]
    assert "setuptools==80.9.0" in calls[install_indices[0]]
    assert any(value.endswith(".whl") for value in calls[install_indices[1]])
    for index in probe_indices:
        assert "PYTHONPATH" not in call_kwargs[index]["env"]
        assert call_kwargs[index]["env"]["PYTHONNOUSERSITE"] == "1"
    metadata = json.loads((pointer.runtime_source / "artifact.json").read_text())
    assert metadata["wheel"] == "famulus_officina-0.1.0-py3-none-any.whl"
    assert len(metadata["wheel_sha256"]) == 64
    assert metadata["source_revision"] == "a" * 40
    assert pointer.repository_config == (repo_root / "officina.toml").resolve()


def test_invalid_repository_config_preserves_prior_pointer(monkeypatch, tmp_path):
    calls: list = []
    monkeypatch.setattr(
        "subprocess.run",
        fake_uv_subprocess_run(calls, trusted_python_dir=tmp_path / "uv-python-store"),
    )
    runtime_root = tmp_path / "runtime"
    manifest = tmp_path / "runtime_dependencies.json"
    manifest.write_text('{"version": 2, "skills": {}}', encoding="utf-8")
    prior = build_candidate_release(
        runtime_root=runtime_root,
        manifest_path=manifest,
        platform="linux",
        uv_bin=FAKE_UV_BIN,
        python_version="3.11",
    )
    prior_pointer = (runtime_root / "current.json").read_bytes()
    bad_repo = tmp_path / "bad-repo"
    bad_repo.mkdir()
    (bad_repo / "officina.toml").write_text("schema_version = 999\n", encoding="utf-8")

    with pytest.raises(ManagedRuntimeError, match="repository configuration"):
        build_candidate_release(
            runtime_root=runtime_root,
            manifest_path=manifest,
            platform="linux",
            uv_bin=FAKE_UV_BIN,
            python_version="3.11",
            repo_root=bad_repo,
        )

    assert (runtime_root / "current.json").read_bytes() == prior_pointer
    assert prior.python_bin.exists()


# famulus-skip: category=capability-unavailable; reason=requires a real uv binary on PATH; alternate=mocked tests above cover call shapes and ordering without uv installed
@pytest.mark.skipif(UV_BIN is None, reason="uv is not installed on this machine")
def test_build_candidate_release_end_to_end_with_real_uv(tmp_path):
    """Integration test against the real uv binary (no mocking): proves the
    venv-creation + batch-install + officina-self-install + activation flow
    actually works, not just that mocked call shapes look right."""
    manifest = tmp_path / "runtime_dependencies.json"
    manifest.write_text(json.dumps({
        "version": 1,
        "skills": {
            "example": {
                "interfaces": {
                    "run": {
                        "dependencies": [
                            {
                                "kind": "python-package",
                                "name": "rich",
                                "version": "any",
                                "platforms": {"linux": True, "macos": True, "windows": True},
                            },
                        ]
                    }
                }
            }
        },
    }))
    runtime_root = tmp_path / "runtime"

    pointer = build_candidate_release(
        runtime_root=runtime_root,
        manifest_path=manifest,
        platform="linux",
        uv_bin=Path(UV_BIN),
        python_version="3.11",
    )

    assert pointer.python_bin.exists()
    assert (runtime_root / "current.json").exists()
    site_packages_has_rich = any(
        p.name.startswith("rich") for p in (pointer.runtime_source / "venv").rglob("rich*")
    )
    assert site_packages_has_rich

    site_packages = _venv_site_packages(pointer.runtime_source / "venv", platform="linux", python_version="3.11")
    assert (site_packages / "officina" / "__init__.py").is_file()
    # Clean env (no inherited PYTHONPATH from whatever ran this test itself)
    # so this actually proves the release venv resolves `officina` from its
    # own copied site-packages, not a source tree the test runner happens to
    # have on its own PYTHONPATH.
    result = subprocess.run(
        [str(pointer.python_bin), "-c", "import officina; print(officina.__file__)"],
        capture_output=True, text=True, env={"PATH": os.environ.get("PATH", "")},
    )
    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == str(site_packages / "officina" / "__init__.py")


# famulus-skip: category=capability-unavailable; reason=requires a real uv binary on PATH; alternate=mocked artifact/probe tests above cover ordering and rollback
@pytest.mark.skipif(UV_BIN is None, reason="uv is not installed on this machine")
def test_repo_candidate_real_uv_runs_installed_dispatcher_through_stable_launcher(tmp_path):
    repo_root = Path(__file__).resolve().parents[1]
    manifest = tmp_path / "runtime_dependencies.json"
    manifest.write_text('{"version": 2, "skills": {}}', encoding="utf-8")

    pointer = build_candidate_release(
        runtime_root=tmp_path / "runtime",
        manifest_path=manifest,
        platform="linux",
        uv_bin=Path(UV_BIN),
        python_version="3.11",
        repo_root=repo_root,
    )

    env = dict(os.environ)
    env.pop("PYTHONPATH", None)
    resolver = tmp_path / "runtime" / "bootstrap" / "resolvers" / "v1" / "launch.py"
    result = subprocess.run(
        [str(resolver), "-m", "officina.dispatcher.cli", "--help"],
        capture_output=True,
        text=True,
        env=env,
    )
    assert result.returncode == 0, result.stderr
    assert "Invoke a skill machine interface" in result.stdout
    metadata = json.loads((pointer.runtime_source / "artifact.json").read_text())
    assert len(metadata["source_revision"]) == 40
    assert set(metadata["source_revision"]) <= set("0123456789abcdef")
