"""Tests for validators/skill_runtime_files.py."""
from __future__ import annotations

import importlib.util
from pathlib import Path
from types import SimpleNamespace


_VALIDATOR = Path(__file__).resolve().parents[1] / "validators" / "skill_runtime_files.py"
_spec = importlib.util.spec_from_file_location("skill_runtime_files", _VALIDATOR)
_mod = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
_spec.loader.exec_module(_mod)


def _write(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("# runtime\n", encoding="utf-8")


def _ordered_files(monkeypatch, tmp_path: Path, *relative_paths: str) -> None:
    paths = []
    for relative_path in relative_paths:
        rel_path = Path(relative_path)
        path = tmp_path / rel_path
        _write(path)
        paths.append((path, rel_path))
    monkeypatch.setattr(_mod, "_iter_skill_files", lambda _repo_root: paths)


def _name_error(relative_path: str, kind: str, component: str) -> str:
    return (
        f"{relative_path}: runtime {kind} must match "
        "`^_[A-Za-z0-9]+(?:_[A-Za-z0-9]+)+$`; "
        f"got `{component}`"
    )


def _suffix_error(relative_path: str, suffix: str) -> str:
    return (
        f"{relative_path}: unsupported runtime suffix `{suffix}`; "
        "allowed suffixes: .py"
    )


def test_valid_and_exempt_runtime_shapes_share_one_owner(tmp_path: Path) -> None:
    for relative_path in (
        "skills/demo-skill/_rtx/_Calendar_Gateway.py",
        "skills/demo-skill/_rtx/__init__.py",
        "skills/demo-skill/_rtx/_install_launcher/_windows_launcher.py",
        "skills/demo-skill/_rtx/_install_launcher/__init__.py",
        "skills/demo-skill/_rtx/._worker_file.py.run.blueprint.yaml",
        "skills/demo-skill/_rtx/._worker_file.py.run.health.json",
        "skills/.system/tool/_rtx/run-task.py",
        "skills/demo-skill/_cx/run-task",
    ):
        _write(tmp_path / relative_path)
    cache = tmp_path / "skills/demo-skill/_rtx/__pycache__/_runtime_gateway.cpython-313.pyc"
    cache.parent.mkdir(parents=True)
    cache.write_bytes(b"generated bytecode")

    assert _mod.validate(tmp_path) == []


def test_invalid_runtime_locations_names_suffixes_and_sidecars_are_exact(
    tmp_path: Path,
    monkeypatch,
) -> None:
    relative_paths = (
        "skills/demo-skill/scripts/_calendar_gateway.py",
        "skills/demo-skill/_rtx/calendar_gateway.py",
        "skills/demo-skill/_rtx/install_launcher/_windows_launcher.py",
        "skills/demo-skill/_rtx/_launcher/__init__.py",
        "skills/demo-skill/_rtx/_gcal.py",
        "skills/demo-skill/_rtx/_get-weather.py",
        "skills/demo-skill/_rtx/_calendar_gateway.txt",
        "skills/demo-skill/_rtx/_worker_file.health.json",
        "skills/demo-skill/_rtx/_mail_transport.sh",
    )
    _ordered_files(monkeypatch, tmp_path, *relative_paths)

    assert _mod.validate(tmp_path) == [
        "skills/demo-skill/scripts/_calendar_gateway.py: skill runtime files "
        "must live under `skills/<skill>/_rtx/`, not `scripts/`",
        _name_error(relative_paths[1], "filename stem", "calendar_gateway"),
        _name_error(relative_paths[2], "directory name", "install_launcher"),
        _name_error(relative_paths[3], "directory name", "_launcher"),
        _name_error(relative_paths[4], "filename stem", "_gcal"),
        _name_error(relative_paths[5], "filename stem", "_get-weather"),
        _suffix_error(relative_paths[6], ".txt"),
        _suffix_error(relative_paths[7], ".json"),
        _name_error(relative_paths[7], "filename stem", "_worker_file.health"),
        _suffix_error(relative_paths[8], ".sh"),
    ]


def test_registered_and_unregistered_fixed_artifacts_are_exact(
    tmp_path: Path,
    monkeypatch,
) -> None:
    child_root = tmp_path / "skills/demo-skill/_rtx"
    registered = (
        "blueprint.yaml", "blueprints/runtime.yaml", "schemas/input.schema.json",
        "assets/data.json", "state/cache.json", "logs/latest.txt",
        "tests/test_runtime.py", ".certificates/runtime.jsonl",
        ".certificate-history/runtime.jsonl", ".pooled-blueprint-review.yaml",
        ".pooled-blueprint-review.health.json", "_run_task.py",
    )
    relative_paths = [f"skills/demo-skill/_rtx/{path}" for path in registered]
    relative_paths.extend((
        "skills/unregistered/_rtx/assets/data.json",
        "skills/root-module/_rtx/assets/data.json",
    ))
    _ordered_files(monkeypatch, tmp_path, *relative_paths)
    graph = SimpleNamespace(
        module_parents={
            "demo-skill": None,
            "demo-skill-rtx": "demo-skill",
            "root-module-rtx": None,
        },
        nodes={
            "demo-skill-rtx": SimpleNamespace(module_root=child_root),
            "root-module-rtx": SimpleNamespace(module_root=tmp_path / "skills/root-module/_rtx"),
        },
        direct_file_owners={},
    )

    assert _mod.validate_with_graph(tmp_path, graph) == [
        _name_error(relative_paths[-2], "directory name", "assets"),
        _suffix_error(relative_paths[-2], ".json"),
        _name_error(relative_paths[-2], "filename stem", "data"),
        _name_error(relative_paths[-1], "directory name", "assets"),
        _suffix_error(relative_paths[-1], ".json"),
        _name_error(relative_paths[-1], "filename stem", "data"),
    ]


def test_gateway_ownership_requires_exact_non_python_behavioral_source(
    tmp_path: Path,
    monkeypatch,
) -> None:
    child_root = tmp_path / "skills/demo-skill/_rtx"
    jobs = child_root / "jobs.yaml"
    python_gateway = child_root / "python.yaml"
    python_payload = child_root / "bin/_owned_payload.py"
    orphan_payload = child_root / "bin/assistant"
    module_gateway = child_root / "module.yaml"
    wrong_gateway = child_root / "wrong.yaml"
    relative_paths = tuple(str(path.relative_to(tmp_path)) for path in (
        jobs,
        python_gateway,
        python_payload,
        orphan_payload,
        module_gateway,
        wrong_gateway,
    ))
    _ordered_files(monkeypatch, tmp_path, *relative_paths)
    yaml_source = "demo-skill-rtx.source.jobs"
    python_source = "demo-skill-rtx.source.python"
    mismatched_source = "demo-skill-rtx.source.wrong"
    graph = SimpleNamespace(
        module_parents={"demo-skill-rtx": "demo-skill"},
        nodes={
            "demo-skill-rtx": SimpleNamespace(module_root=child_root),
            yaml_source: SimpleNamespace(
                node_type="behavioral_source", gateway_path=jobs,
                declaration={"gateway": {"language": "YAML"}},
            ),
            python_source: SimpleNamespace(
                node_type="behavioral_source", gateway_path=python_gateway,
                declaration={"gateway": {"language": "Python"}},
            ),
            "owned-module": SimpleNamespace(
                node_type="module", gateway_path=module_gateway,
                declaration={"gateway": {"language": "YAML"}},
            ),
            mismatched_source: SimpleNamespace(
                node_type="behavioral_source", gateway_path=child_root / "other.yaml",
                declaration={"gateway": {"language": "YAML"}},
            ),
        },
        direct_file_owners={
            jobs: yaml_source,
            python_gateway: python_source,
            python_payload: python_source,
            module_gateway: "owned-module",
            wrong_gateway: mismatched_source,
        },
    )

    assert _mod.validate_with_graph(tmp_path, graph) == [
        _suffix_error(relative_paths[1], ".yaml"),
        _name_error(relative_paths[1], "filename stem", "python"),
        _name_error(relative_paths[2], "directory name", "bin"),
        _name_error(relative_paths[3], "directory name", "bin"),
        _suffix_error(relative_paths[3], ""),
        _name_error(relative_paths[3], "filename stem", "assistant"),
        _suffix_error(relative_paths[4], ".yaml"),
        _name_error(relative_paths[4], "filename stem", "module"),
        _suffix_error(relative_paths[5], ".yaml"),
        _name_error(relative_paths[5], "filename stem", "wrong"),
    ]


def test_deepest_child_and_root_module_behavior_preserves_compatibility_wrapper(
    tmp_path: Path,
) -> None:
    root = tmp_path / "modules/root"
    parent = root / "parent"
    nested = parent / "assets/nested"
    nested_fixed = nested / "assets/data.json"
    nested_payload = nested / "bin/_owned_payload.py"
    root_artifact = root / "assets/data.json"
    graph = SimpleNamespace(
        module_parents={"root": None, "parent": "root", "nested": "parent"},
        nodes={
            "root": SimpleNamespace(module_root=root),
            "parent": SimpleNamespace(module_root=parent),
            "nested": SimpleNamespace(module_root=nested),
        },
        direct_file_owners={},
    )
    index = _mod._build_child_artifact_index(graph)

    assert index == (frozenset({parent, nested}), frozenset())
    assert [_mod._is_registered_child_artifact(path, *index) for path in (
        nested_fixed, nested_payload, root_artifact,
    )] == [True, False, False]
    assert [_mod._registered_child_artifact(path, graph) for path in (
        nested_fixed, nested_payload, root_artifact,
    )] == [True, False, False]
    assert _mod._registered_child_artifact(nested_fixed, None) is False
    assert _mod._build_child_artifact_index(None) == (frozenset(), frozenset())


def test_casefold_collisions_retain_exact_order_and_paths(
    tmp_path: Path,
    monkeypatch,
) -> None:
    relative_paths = (
        "skills/demo-skill/_rtx/_Calendar_Gateway.py",
        "skills/demo-skill/_rtx/_calendar_gateway.py",
        "skills/demo-skill/_rtx/_Install_Launcher/_linux_launcher.py",
        "skills/demo-skill/_rtx/_install_launcher/_osx_launcher.py",
    )
    _ordered_files(monkeypatch, tmp_path, *relative_paths)

    assert _mod.validate(tmp_path) == [
        "skills/demo-skill/_rtx/_calendar_gateway.py: case-insensitive runtime "
        "path collision with skills/demo-skill/_rtx/_Calendar_Gateway.py",
        "skills/demo-skill/_rtx/_install_launcher: case-insensitive runtime "
        "path collision with skills/demo-skill/_rtx/_Install_Launcher",
    ]


def test_git_ignored_security_boundary_and_fail_closed_paths(
    tmp_path: Path,
    monkeypatch,
) -> None:
    ignored_rel = Path("skills/demo-skill/_rtx/_bad_file.sh")
    sibling_rel = Path("skills/demo-skill/_rtx/_bad_sibling.sh")
    ignored = tmp_path / ignored_rel
    sibling = tmp_path / sibling_rel
    _write(ignored)
    _write(sibling)
    monkeypatch.setattr(Path, "rglob", lambda _root, _pattern: iter((ignored, sibling)))
    outcomes = [
        SimpleNamespace(returncode=0, stdout=f"{ignored_rel.as_posix()}\0"),
        OSError("git unavailable"),
        SimpleNamespace(returncode=128, stdout=""),
    ]
    calls = []

    def fake_run(command, **kwargs):
        calls.append((command, kwargs))
        outcome = outcomes.pop(0)
        if isinstance(outcome, BaseException):
            raise outcome
        return outcome

    monkeypatch.setattr(_mod.subprocess, "run", fake_run)

    sibling_error = _suffix_error(sibling_rel.as_posix(), ".sh")
    both_errors = [
        _suffix_error(ignored_rel.as_posix(), ".sh"),
        sibling_error,
    ]
    assert _mod.validate(tmp_path) == [sibling_error]
    assert _mod.validate(tmp_path) == both_errors
    assert _mod.validate(tmp_path) == both_errors
    assert len(calls) == 3
    assert calls[0][0] == [
        "git", "-C", str(tmp_path), "ls-files", "--others", "--ignored",
        "--exclude-standard", "-z",
    ]
    assert calls[0][1] == {
        "capture_output": True, "text": True, "encoding": "utf-8",
        "errors": "replace", "check": False, "timeout": 30,
    }


def test_validation_builds_one_index_without_pairwise_root_comparisons(
    tmp_path: Path,
    monkeypatch,
) -> None:
    class CountingMapping(dict):
        items_calls = 0

        def items(self):
            self.items_calls += 1
            return super().items()

    module_parents = CountingMapping()
    direct_file_owners = CountingMapping()
    nodes = {}
    for index in range(4):
        module_id = f"child-{index}"
        child_root = tmp_path / f"skills/demo-skill/_rtx/_child_{index}"
        artifact = child_root / "assets/data.json"
        gateway = child_root / "jobs.yaml"
        _write(artifact)
        _write(gateway)
        source_id = f"{module_id}.source.jobs"
        module_parents[module_id] = "demo-skill"
        nodes[module_id] = SimpleNamespace(module_root=child_root)
        nodes[source_id] = SimpleNamespace(
            node_type="behavioral_source", gateway_path=gateway,
            declaration={"gateway": {"language": "YAML"}},
        )
        direct_file_owners[gateway] = source_id
    graph = SimpleNamespace(
        module_parents=module_parents,
        nodes=nodes,
        direct_file_owners=direct_file_owners,
    )
    original_is_relative_to = Path.is_relative_to
    pairwise_calls = []

    def counting_is_relative_to(path: Path, other: Path) -> bool:
        pairwise_calls.append((path, other))
        return original_is_relative_to(path, other)

    monkeypatch.setattr(Path, "is_relative_to", counting_is_relative_to)

    assert _mod.validate_with_graph(tmp_path, graph) == []
    assert module_parents.items_calls == 1
    assert direct_file_owners.items_calls == 1
    assert pairwise_calls == []
