#!/usr/bin/env python3
"""
scaffold.py — Install the universal dispatcher/invoke-skill launchers.

This is the Phase-1 floor: every skill's SKILL.md invokes scripts via a bare
`dispatcher --caller-skill ...` command, and recurring-tasks systemd/cron
jobs invoke `invoke-skill <name>`. Both need to exist and be on PATH
regardless of plugin vs dev-mode, and regardless of which agent launchers
(assistant/collab/coauthor/tw) the user wants. Run this first, always.

Also installs required third-party Python packages declared by blueprint
executable interfaces, not tied to any particular agent.

Does NOT set ASSISTANT_DEFAULT (see launchers.py) or AI (see dev_link.py) —
this subcommand only owns PATH.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

REPO_SRC = Path(__file__).resolve().parents[3] / "src"
if str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from officina.runtime.python_machine_interface import PythonArgvMachineInterface

from _state_record import Manifest, manifest_path
from _shell_block import ensure_rc_vars


def log(msg: str = "") -> None:
    print(msg, flush=True)


RUNTIME_DEPENDENCIES_MANIFEST = Path("references") / "blueprint" / "runtime_dependencies.json"


class CapabilityResult:
    """Outcome for one scaffold capability that downstream workflows rely on."""

    def __init__(
        self,
        *,
        name: str,
        required: bool,
        status: str,
        workflows: tuple[str, ...],
        reason: str = "",
    ) -> None:
        self.name = name
        self.required = required
        self.status = status
        self.workflows = workflows
        self.reason = reason

    def blocks_install(self) -> bool:
        """Return whether this outcome leaves a required capability unavailable."""
        return self.required and self.status in {"skipped", "failed"}


DISPATCHER_WORKFLOWS = (
    "machine-interface dispatch",
    "SKILL.md interface invocation",
)
INVOKE_SKILL_WORKFLOWS = (
    "recurring automation",
    "systemd/cron skill invocation",
)


def required_python_packages(repo_root: Path) -> list[str]:
    packages: set[str] = set()
    manifest = repo_root / RUNTIME_DEPENDENCIES_MANIFEST
    if manifest.exists():
        data = json.loads(manifest.read_text(encoding="utf-8"))
        manifest_packages = data.get("all", {}).get("python", [])
        if isinstance(manifest_packages, list):
            packages.update(package for package in manifest_packages if isinstance(package, str) and package)
    return sorted(packages, key=str.lower)


def install_python_packages(repo_root: Path, dry_run: bool) -> None:
    """Ensure required third-party Python packages are installed.

    officina.dispatcher itself (first-party) is deliberately NOT pip-installed
    here — it runs from the repo via the dispatcher launcher below.
    """
    log("\nInstalling required Python packages...")
    for package in required_python_packages(repo_root):
        if dry_run:
            log(f"  (dry-run) Would install: {package}")
            continue
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", package, "--quiet"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="strict",
        )
        if result.returncode == 0:
            log(f"  OK: {package}")
        else:
            log(f"  WARN: failed to install {package}: {result.stderr.strip()}")


def install_dispatcher_launcher(
    repo_root: Path,
    bin_dir: Path,
    dry_run: bool,
    manifest: Manifest | None = None,
) -> CapabilityResult:
    """Write a `dispatcher` launcher into the managed bin dir.

    First-party code is never pip-installed: the repo ($AI) is the single
    source of truth, and installed copies drift. The launcher runs
    officina.dispatcher straight from the repo source. $AI is used when set
    (shell contexts); the install-time repo path is baked in as a fallback
    for contexts without it (systemd, cron).
    """
    if sys.platform == "win32":
        return CapabilityResult(
            name="dispatcher",
            required=True,
            status="skipped",
            workflows=DISPATCHER_WORKFLOWS,
            reason="managed bin launchers are POSIX shell on this host",
        )

    launcher = bin_dir / "dispatcher"
    content = (
        "#!/bin/bash\n"
        "# Generated by install-assistant-tools - do not edit manually.\n"
        "# Runs officina.dispatcher directly from the repo ($AI): first-party code\n"
        "# is never pip-installed, so there is no second copy to drift or break.\n"
        f'AI="${{AI:-{repo_root}}}"\n'
        'export PYTHONPATH="$AI/src${PYTHONPATH:+:$PYTHONPATH}"\n'
        'exec python3 -m officina.dispatcher.cli "$@"\n'
    )

    if dry_run:
        log(f"Would write {launcher}")
        return CapabilityResult(
            name="dispatcher",
            required=True,
            status="would-install",
            workflows=DISPATCHER_WORKFLOWS,
        )

    bin_dir.mkdir(parents=True, exist_ok=True)
    launcher.write_text(content)
    launcher.chmod(0o755)
    log(f"  Wrote dispatcher launcher: {launcher}")
    if manifest is not None:
        manifest.record("file", path=str(launcher))
    return CapabilityResult(
        name="dispatcher",
        required=True,
        status="installed",
        workflows=DISPATCHER_WORKFLOWS,
    )


def install_invoke_skill_launcher(
    bin_dir: Path,
    dry_run: bool,
    manifest: Manifest | None = None,
) -> CapabilityResult:
    """Write an `invoke-skill` launcher into the managed bin dir.

    Used by AI_AGENT_COMMAND_TEMPLATE to invoke skills from systemd timers
    and cron jobs. Resolves $CLAUDE_HOME at runtime with fallback to
    ~/.claude, so it works regardless of --home overrides used at install
    time.
    """
    if sys.platform == "win32":
        return CapabilityResult(
            name="invoke-skill",
            required=True,
            status="skipped",
            workflows=INVOKE_SKILL_WORKFLOWS,
            reason="managed bin launchers are POSIX shell on this host",
        )

    launcher = bin_dir / "invoke-skill"
    content = (
        "#!/bin/bash\n"
        "# Generated by install-assistant-tools - do not edit manually.\n"
        "# Invokes a skill via the assistant command for recurring tasks.\n"
        "# Uses $CLAUDE_HOME to find the recurring-tasks skill at runtime.\n"
        "set -euo pipefail\n"
        "\n"
        "if [[ $# -ne 1 ]]; then\n"
        "  echo 'Usage: invoke-skill <skill-name>' >&2\n"
        "  exit 2\n"
        "fi\n"
        "\n"
        "skill=\"$1\"\n"
        "claude_home=\"${CLAUDE_HOME:-$HOME/.claude}\"\n"
        "recurring_tasks_dir=\"$claude_home/skills/recurring-tasks\"\n"
        "invoke_agent=\"$recurring_tasks_dir/_rtx/_agent_invoker.sh\"\n"
        "\n"
        "if [[ ! -x \"$invoke_agent\" ]]; then\n"
        "  echo \"ERROR: invoke-agent.sh not found at: $invoke_agent\" >&2\n"
        "  exit 1\n"
        "fi\n"
        "\n"
        "exec \"$invoke_agent\" \"$skill\"\n"
    )

    if dry_run:
        log(f"Would write {launcher}")
        return CapabilityResult(
            name="invoke-skill",
            required=True,
            status="would-install",
            workflows=INVOKE_SKILL_WORKFLOWS,
        )

    bin_dir.mkdir(parents=True, exist_ok=True)
    launcher.write_text(content)
    launcher.chmod(0o755)
    log(f"  Wrote invoke-skill launcher: {launcher}")
    if manifest is not None:
        manifest.record("file", path=str(launcher))
    return CapabilityResult(
        name="invoke-skill",
        required=True,
        status="installed",
        workflows=INVOKE_SKILL_WORKFLOWS,
    )


def report_capabilities(results: list[CapabilityResult]) -> int:
    """Print scaffold capability status and return the aggregate exit status."""
    if not results:
        return 0

    log("")
    log("Scaffold capability report:")
    for result in results:
        if result.blocks_install():
            label = "FAILED"
        elif result.status == "would-install":
            label = "WOULD-INSTALL"
        elif result.status == "installed":
            label = "OK"
        else:
            label = result.status.upper()

        log(f"  {label}: {result.name}")
        if result.reason:
            log(f"    reason: {result.reason}")
        log(f"    affected workflows: {', '.join(result.workflows)}")

    if any(result.blocks_install() for result in results):
        log("")
        log("Scaffold failed: required capabilities were not installed.")
        return 1
    return 0


def ensure_path_windows(bin_dir: Path, dry_run: bool, manifest: Manifest | None = None) -> None:
    """Add bin_dir to the Windows user PATH via the registry (PATH only)."""
    if dry_run:
        log(f"  Would add to user PATH (registry): {bin_dir}")
        return

    import winreg

    REG_PATH = "Environment"
    with winreg.OpenKey(
        winreg.HKEY_CURRENT_USER, REG_PATH, 0,
        winreg.KEY_READ | winreg.KEY_WRITE,
    ) as key:
        try:
            current_path, path_type = winreg.QueryValueEx(key, "PATH")
        except FileNotFoundError:
            current_path, path_type = "", winreg.REG_EXPAND_SZ

        bin_str = str(bin_dir)
        parts = [p for p in current_path.split(";") if p]
        if bin_str not in parts:
            new_path = ";".join([bin_str] + parts)
            winreg.SetValueEx(key, "PATH", 0, path_type, new_path)
            log(f"  Added to user PATH: {bin_dir}")
        else:
            log(f"  User PATH already contains: {bin_dir}")

    if manifest is not None:
        manifest.record("registry_env", path=str(bin_dir), names=["PATH"])


def run(
    *,
    repo_root: Path,
    home: Path | None = None,
    bin_dir: Path | None = None,
    shell_rc: Path | None = None,
    dry_run: bool = False,
    manifest: Manifest | None = None,
) -> int:
    home = home or Path.home()
    bin_dir = bin_dir or home / "Documents" / "_rtx" / "bin"

    if manifest is None and not dry_run:
        manifest = Manifest(manifest_path(home))
    if dry_run:
        manifest = None

    install_python_packages(repo_root, dry_run)
    capability_results = [
        install_dispatcher_launcher(repo_root, bin_dir, dry_run, manifest),
        install_invoke_skill_launcher(bin_dir, dry_run, manifest),
    ]

    if sys.platform == "win32":
        ensure_path_windows(bin_dir, dry_run, manifest)
    else:
        if shell_rc is None:
            detected_shell = os.environ.get("SHELL", "")
            shell_rc = home / (".zshrc" if "zsh" in detected_shell else ".bashrc")
        ensure_rc_vars(
            shell_rc,
            {"PATH": f'export PATH="{bin_dir}:$PATH"'},
            dry_run,
            manifest,
            label="user",
        )

    if manifest is not None:
        manifest.save()

    status = report_capabilities(capability_results)

    log("")
    log("Scaffold complete." if status == 0 else "Scaffold incomplete.")
    log(f"  Bin dir: {bin_dir}")
    return status


class Interface(PythonArgvMachineInterface):
    prog = "install_scaffold.py"

    def run(self, argv: list[str]) -> int:
        return main(argv)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--repo-root", metavar="DIR", required=True, help="Path to the AI repo checkout")
    parser.add_argument("--home", metavar="DIR", help="Home directory (default: platform home)")
    parser.add_argument("--bin-dir", metavar="DIR", help="Bin dir for launchers (default: ~/Documents/scripts/bin)")
    parser.add_argument("--shell-rc", metavar="FILE", help="Shell rc file (auto-detected on Unix)")
    parser.add_argument("--dry-run", action="store_true", help="Print planned actions without writing")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    return run(
        repo_root=Path(args.repo_root),
        home=Path(args.home) if args.home else None,
        bin_dir=Path(args.bin_dir) if args.bin_dir else None,
        shell_rc=Path(args.shell_rc) if args.shell_rc else None,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    raise SystemExit(main())
