#!/bin/bash
# Invokes a skill via the assistant command, for use by run-skill.sh.
# Usage: invoke-agent.sh <skill-name>
set -euo pipefail

skill="$1"

# Source the repo-local env to get assistant on PATH without touching system
# profiles. Generated by install_assistant_tools.sh; gitignored.
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
env_file="$script_dir/env.sh"
if [[ -f "$env_file" ]]; then
  # shellcheck source=/dev/null
  source "$env_file"
fi

exec assistant --permission-mode bypassPermissions -p "/$skill"
