"""Linux launcher bundle installer."""
from __future__ import annotations

from pathlib import Path

from _state_record import Manifest

from ._base_launcher import (
    DISPATCHER_WORKFLOWS,
    INVOKE_SKILL_WORKFLOWS,
    LauncherBundleSpec,
    LauncherFileSpec,
    LauncherInstallResult,
    LauncherInstallerBase,
)


def _unix_dispatcher_content(repo_root: Path) -> str:
    repo = repr(str(repo_root))
    return (
        "#!/usr/bin/env python3\n"
        "# Generated by install-assistant-tools - do not edit manually.\n"
        "\"\"\"Run officina.dispatcher directly from the repo checkout.\"\"\"\n"
        "import os\n"
        "import runpy\n"
        "import sys\n"
        "\n"
        f"ai_root = os.environ.get('AI', {repo})\n"
        "sys.path.insert(0, os.path.join(ai_root, 'src'))\n"
        "sys.argv = ['officina.dispatcher.cli', *sys.argv[1:]]\n"
        "runpy.run_module('officina.dispatcher.cli', run_name='__main__')\n"
    )


def _unix_invoke_skill_content() -> str:
    return (
        "#!/usr/bin/env python3\n"
        "# Generated by install-assistant-tools - do not edit manually.\n"
        "\"\"\"Invoke a skill through the selected assistant backend.\"\"\"\n"
        "import os\n"
        "import sys\n"
        "\n"
        "if len(sys.argv) != 2:\n"
        "    print('Usage: invoke-skill <skill-name>', file=sys.stderr)\n"
        "    raise SystemExit(2)\n"
        "\n"
        "skill = sys.argv[1]\n"
        "backend = os.environ.get('ASSISTANT_DEFAULT', 'claude')\n"
        "\n"
        "if backend == 'claude':\n"
        "    command = [\n"
        "        'assistant', '--local', '--claude', '--permission-mode',\n"
        "        'bypassPermissions', '-p', f'/{skill}',\n"
        "    ]\n"
        "elif backend == 'codex':\n"
        "    command = [\n"
        "        'assistant', '--local', '--codex', 'exec', '--skip-git-repo-check',\n"
        "        '--dangerously-bypass-approvals-and-sandbox', f'${skill}',\n"
        "    ]\n"
        "else:\n"
        "    print(f'Unknown ASSISTANT_DEFAULT backend: {backend}', file=sys.stderr)\n"
        "    raise SystemExit(2)\n"
        "\n"
        "try:\n"
        "    os.execvp(command[0], command)\n"
        "except FileNotFoundError:\n"
        "    print(f'Command not found: {command[0]}', file=sys.stderr)\n"
        "    raise SystemExit(127)\n"
    )


class LinuxLauncherInstaller(LauncherInstallerBase):
    """Install launcher bundles on Linux-like hosts."""

    static_launcher_mode = "link"

    def install_dispatcher_launcher(
        self,
        repo_root: Path,
        bin_dir: Path,
        dry_run: bool,
        manifest: Manifest | None = None,
    ) -> LauncherInstallResult:
        bundle = LauncherBundleSpec(
            name="dispatcher",
            workflows=DISPATCHER_WORKFLOWS,
            files=[
                LauncherFileSpec(
                    destination=bin_dir / "dispatcher",
                    mode="generate",
                    content=_unix_dispatcher_content(repo_root),
                    executable=True,
                )
            ],
        )
        return self.install_bundle(bundle, dry_run=dry_run, manifest=manifest)

    def install_invoke_skill_launcher(
        self,
        bin_dir: Path,
        dry_run: bool,
        manifest: Manifest | None = None,
    ) -> LauncherInstallResult:
        bundle = LauncherBundleSpec(
            name="invoke-skill",
            workflows=INVOKE_SKILL_WORKFLOWS,
            files=[
                LauncherFileSpec(
                    destination=bin_dir / "invoke-skill",
                    mode="generate",
                    content=_unix_invoke_skill_content(),
                    executable=True,
                )
            ],
        )
        return self.install_bundle(bundle, dry_run=dry_run, manifest=manifest)

    def install_agent_launcher_files(
        self,
        *,
        source_bin_dir: Path,
        bin_dir: Path,
        agent: str,
        dry_run: bool,
        manifest: Manifest | None,
    ) -> None:
        if agent == "tw":
            bundle = LauncherBundleSpec(
                name="tw",
                required=False,
                workflows=("tmux workspace launcher",),
                files=[
                    LauncherFileSpec(
                        source=source_bin_dir / "tmux-workspace",
                        destination=bin_dir / "tmux-workspace",
                        mode=self.static_launcher_mode,
                    ),
                    LauncherFileSpec(
                        source=source_bin_dir / "tmux-workspace",
                        destination=bin_dir / "tw",
                        mode=self.static_launcher_mode,
                    ),
                ],
            )
        else:
            bundle = LauncherBundleSpec(
                name=agent,
                required=False,
                workflows=("agent launcher",),
                files=self._agent_launcher_files(source_bin_dir, bin_dir, agent),
            )
        self.install_bundle(bundle, dry_run=dry_run, manifest=manifest)
