"""Linux launcher bundle installer."""
from __future__ import annotations

import sys
import os
from pathlib import Path
from typing import Mapping

if __package__ and __package__.count('.') >= 1:
    from .._state_record import Manifest
else:
    from _state_record import Manifest

from officina.common.famulus_paths import resolve_famulus_paths

from officina.common.command_files import (
    LauncherBundleSpec,
    LauncherFileSpec,
    LauncherInstallResult,
    LauncherInstallerBase,
)
from . import (
    DISPATCHER_WORKFLOWS,
    INVOKE_SKILL_WORKFLOWS,
    WAKEUP_COMMANDS,
    WAKEUP_WORKFLOWS,
)

# Fixed, immutable location of the stable launch resolver beneath a given
# runtime_root. The file deployed there is officina.install.resolvers.launch's
# source (a dependency-free, stdlib-only script -- deployment is the
# managed-runtime install flow's job, not this generator's). Generated shims
# invoke this path instead of embedding a release-specific repo checkout or
# interpreter: this path does not change when the repo moves or a new release
# is activated.
_RESOLVER_RELATIVE_PATH = ("bootstrap", "resolvers", "v1", "launch.py")


def _resolver_path(
    *,
    home: Path | None = None,
    environ: Mapping[str, str] | None = None,
    runtime_root: Path | None = None,
) -> Path:
    """Return the fixed resolver path beneath this host's runtime_root."""
    home = home or Path.home()
    if runtime_root is None:
        runtime_root = resolve_famulus_paths(
            platform=sys.platform,
            home=home,
            environ=os.environ if environ is None else environ,
        ).runtime_root
    return runtime_root.joinpath(*_RESOLVER_RELATIVE_PATH)


def _unix_module_content(
    module: str,
    description: str,
    *,
    home: Path | None = None,
    environ: Mapping[str, str] | None = None,
    fixed_args: tuple[str, ...] = (),
    help_name: str | None = None,
    runtime_root: Path | None = None,
) -> str:
    """Render one POSIX shim that delegates a module to the active release.

    The generated program intentionally knows only the stable resolver path and
    the target module. The resolver owns release selection and interpreter
    handoff, so reinstalling a release never makes this user-bin shim stale.
    """
    resolver = repr(str(_resolver_path(home=home, environ=environ, runtime_root=runtime_root)))
    local_help = (
        "if sys.argv[1:] and sys.argv[1] in ('-h', '--help'):\n"
        f"    print('Usage: {help_name} [--local] [--claude|--codex] [args...]')\n"
        "    raise SystemExit(0)\n"
        if help_name is not None
        else ""
    )
    return (
        "#!/usr/bin/env python3\n"
        "# Generated by install-assistant-tools - do not edit manually.\n"
        f'"""{description}"""\n'
        "import os\n"
        "import sys\n"
        "\n"
        f"{local_help}"
        f"RESOLVER = {resolver}\n"
        f"os.execv(RESOLVER, [RESOLVER, '-m', {module!r}, "
        f"*{fixed_args!r}, *sys.argv[1:]])\n"
    )


def _unix_dispatcher_content(
    repo_root: Path, *, home: Path | None = None, runtime_root: Path | None = None
) -> str:
    """Preserve the established dispatcher renderer API for external tests."""
    return _unix_module_content(
        "officina.dispatcher.cli",
        "Run officina.dispatcher.cli via the stable managed-runtime resolver.",
        home=home,
        runtime_root=runtime_root,
    )


def _unix_invoke_skill_content(
    *,
    home: Path | None = None,
    environ: Mapping[str, str] | None = None,
    runtime_root: Path | None = None,
) -> str:
    return _unix_module_content(
        "officina.launchers.agent",
        "Invoke one skill through the managed background agent policy.",
        home=home,
        environ=environ,
        runtime_root=runtime_root,
        fixed_args=("--invoke-skill",),
    )


class LinuxLauncherInstaller(LauncherInstallerBase):
    """Install launcher bundles on Linux-like hosts."""

    static_launcher_mode = "link"

    def install_dispatcher_launcher(
        self,
        repo_root: Path,
        bin_dir: Path,
        dry_run: bool,
        manifest: Manifest | None = None,
        *,
        home: Path | None = None,
        runtime_root: Path | None = None,
    ) -> LauncherInstallResult:
        bundle = LauncherBundleSpec(
            name="dispatcher",
            workflows=DISPATCHER_WORKFLOWS,
            files=[
                LauncherFileSpec(
                    destination=bin_dir / "dispatcher",
                    mode="generate",
                    content=_unix_dispatcher_content(repo_root, home=home, runtime_root=runtime_root),
                    executable=True,
                )
            ],
        )
        return self.install_bundle(bundle, dry_run=dry_run, manifest=manifest)

    def install_invoke_skill_launcher(
        self,
        bin_dir: Path,
        dry_run: bool,
        manifest: Manifest | None = None,
        *,
        home: Path | None = None,
        runtime_root: Path | None = None,
    ) -> LauncherInstallResult:
        bundle = LauncherBundleSpec(
            name="invoke-skill",
            workflows=INVOKE_SKILL_WORKFLOWS,
            files=[
                LauncherFileSpec(
                    destination=bin_dir / "invoke-skill",
                    mode="generate",
                    content=_unix_invoke_skill_content(home=home, runtime_root=runtime_root),
                    executable=True,
                ),
                LauncherFileSpec(
                    destination=bin_dir / "background_run",
                    mode="generate",
                    content=_unix_module_content(
                        "officina.launchers.agent",
                        "Launch the scheduler-owned background agent.",
                        home=home,
                        runtime_root=runtime_root,
                        fixed_args=("--agent", "background_run"),
                    ),
                    executable=True,
                ),
            ],
        )
        return self.install_bundle(bundle, dry_run=dry_run, manifest=manifest)

    def install_wakeup_launcher(
        self,
        bin_dir: Path,
        dry_run: bool,
        manifest: Manifest | None = None,
        *,
        home: Path | None = None,
        runtime_root: Path | None = None,
    ) -> LauncherInstallResult:
        """Install both public wakeup names as resolver-backed POSIX shims."""
        content = _unix_module_content(
            "officina.wakeup.cli",
            "Run officina.wakeup.cli via the stable managed-runtime resolver.",
            home=home,
            runtime_root=runtime_root,
        )
        bundle = LauncherBundleSpec(
            name="llm-wakeup",
            workflows=WAKEUP_WORKFLOWS,
            files=[
                LauncherFileSpec(
                    destination=bin_dir / command,
                    mode="generate",
                    content=content,
                    executable=True,
                )
                for command in WAKEUP_COMMANDS
            ],
        )
        return self.install_bundle(bundle, dry_run=dry_run, manifest=manifest)
