"""Linux launcher bundle installer."""
from __future__ import annotations

import sys
from pathlib import Path

if __package__ and __package__.count('.') >= 1:
    from .._state_record import Manifest
else:
    from _state_record import Manifest

from officina.common.famulus_paths import resolve_famulus_paths

from ._base_launcher import (
    DISPATCHER_WORKFLOWS,
    INVOKE_SKILL_WORKFLOWS,
    WAKEUP_COMMANDS,
    WAKEUP_WORKFLOWS,
    LauncherBundleSpec,
    LauncherFileSpec,
    LauncherInstallResult,
    LauncherInstallerBase,
)

# Fixed, immutable location of the stable launch resolver beneath a given
# runtime_root. The file deployed there is officina.install.resolvers.launch's
# source (a dependency-free, stdlib-only script -- deployment is the
# managed-runtime install flow's job, not this generator's). Generated shims
# invoke this path instead of embedding a release-specific repo checkout or
# interpreter: this path does not change when the repo moves or a new release
# is activated.
_RESOLVER_RELATIVE_PATH = ("bootstrap", "resolvers", "v1", "launch.py")


def _resolver_path(*, home: Path | None = None) -> Path:
    """Return the fixed resolver path beneath this host's runtime_root."""
    home = home or Path.home()
    runtime_root = resolve_famulus_paths(platform=sys.platform, home=home).runtime_root
    return runtime_root.joinpath(*_RESOLVER_RELATIVE_PATH)


def _unix_module_content(
    module: str,
    description: str,
    *,
    home: Path | None = None,
) -> str:
    """Render one POSIX shim that delegates a module to the active release.

    The generated program intentionally knows only the stable resolver path and
    the target module. The resolver owns release selection and interpreter
    handoff, so reinstalling a release never makes this user-bin shim stale.
    """
    resolver = repr(str(_resolver_path(home=home)))
    return (
        "#!/usr/bin/env python3\n"
        "# Generated by install-assistant-tools - do not edit manually.\n"
        f'"""{description}"""\n'
        "import os\n"
        "import sys\n"
        "\n"
        f"RESOLVER = {resolver}\n"
        f"os.execv(RESOLVER, [RESOLVER, '-m', {module!r}, *sys.argv[1:]])\n"
    )


def _unix_dispatcher_content(repo_root: Path, *, home: Path | None = None) -> str:
    """Preserve the established dispatcher renderer API for external tests."""
    return _unix_module_content(
        "officina.dispatcher.cli",
        "Run officina.dispatcher.cli via the stable managed-runtime resolver.",
        home=home,
    )


def _unix_invoke_skill_content() -> str:
    return (
        "#!/usr/bin/env python3\n"
        "# Generated by install-assistant-tools - do not edit manually.\n"
        "\"\"\"Invoke a skill through the selected assistant backend.\"\"\"\n"
        "import os\n"
        "import sys\n"
        "\n"
        "if len(sys.argv) != 2:\n"
        "    print('Usage: invoke-skill <skill-name>', file=sys.stderr)\n"
        "    raise SystemExit(2)\n"
        "\n"
        "skill = sys.argv[1]\n"
        "backend = os.environ.get('ASSISTANT_DEFAULT', 'claude')\n"
        "\n"
        "if backend == 'claude':\n"
        "    command = [\n"
        "        'assistant', '--local', '--claude', '--permission-mode',\n"
        "        'bypassPermissions', '-p', f'/{skill}',\n"
        "    ]\n"
        "elif backend == 'codex':\n"
        "    command = [\n"
        "        'assistant', '--local', '--codex', 'exec', '--skip-git-repo-check',\n"
        "        '--dangerously-bypass-approvals-and-sandbox', f'${skill}',\n"
        "    ]\n"
        "else:\n"
        "    print(f'Unknown ASSISTANT_DEFAULT backend: {backend}', file=sys.stderr)\n"
        "    raise SystemExit(2)\n"
        "\n"
        "try:\n"
        "    os.execvp(command[0], command)\n"
        "except FileNotFoundError:\n"
        "    print(f'Command not found: {command[0]}', file=sys.stderr)\n"
        "    raise SystemExit(127)\n"
    )


class LinuxLauncherInstaller(LauncherInstallerBase):
    """Install launcher bundles on Linux-like hosts."""

    static_launcher_mode = "link"

    def install_dispatcher_launcher(
        self,
        repo_root: Path,
        bin_dir: Path,
        dry_run: bool,
        manifest: Manifest | None = None,
        *,
        home: Path | None = None,
    ) -> LauncherInstallResult:
        bundle = LauncherBundleSpec(
            name="dispatcher",
            workflows=DISPATCHER_WORKFLOWS,
            files=[
                LauncherFileSpec(
                    destination=bin_dir / "dispatcher",
                    mode="generate",
                    content=_unix_dispatcher_content(repo_root, home=home),
                    executable=True,
                )
            ],
        )
        return self.install_bundle(bundle, dry_run=dry_run, manifest=manifest)

    def install_invoke_skill_launcher(
        self,
        bin_dir: Path,
        dry_run: bool,
        manifest: Manifest | None = None,
    ) -> LauncherInstallResult:
        bundle = LauncherBundleSpec(
            name="invoke-skill",
            workflows=INVOKE_SKILL_WORKFLOWS,
            files=[
                LauncherFileSpec(
                    destination=bin_dir / "invoke-skill",
                    mode="generate",
                    content=_unix_invoke_skill_content(),
                    executable=True,
                )
            ],
        )
        return self.install_bundle(bundle, dry_run=dry_run, manifest=manifest)

    def install_wakeup_launcher(
        self,
        bin_dir: Path,
        dry_run: bool,
        manifest: Manifest | None = None,
        *,
        home: Path | None = None,
    ) -> LauncherInstallResult:
        """Install both public wakeup names as resolver-backed POSIX shims."""
        content = _unix_module_content(
            "officina.wakeup.cli",
            "Run officina.wakeup.cli via the stable managed-runtime resolver.",
            home=home,
        )
        bundle = LauncherBundleSpec(
            name="llm-wakeup",
            workflows=WAKEUP_WORKFLOWS,
            files=[
                LauncherFileSpec(
                    destination=bin_dir / command,
                    mode="generate",
                    content=content,
                    executable=True,
                )
                for command in WAKEUP_COMMANDS
            ],
        )
        return self.install_bundle(bundle, dry_run=dry_run, manifest=manifest)

    def install_agent_launcher_files(
        self,
        *,
        source_bin_dir: Path,
        bin_dir: Path,
        agent: str,
        dry_run: bool,
        manifest: Manifest | None,
    ) -> None:
        if agent == "tw":
            bundle = LauncherBundleSpec(
                name="tw",
                required=False,
                workflows=("tmux workspace launcher",),
                files=[
                    LauncherFileSpec(
                        source=source_bin_dir / "tmux-workspace",
                        destination=bin_dir / "tmux-workspace",
                        mode=self.static_launcher_mode,
                    ),
                    LauncherFileSpec(
                        source=source_bin_dir / "tmux-workspace",
                        destination=bin_dir / "tw",
                        mode=self.static_launcher_mode,
                    ),
                ],
            )
        else:
            bundle = LauncherBundleSpec(
                name=agent,
                required=False,
                workflows=("agent launcher",),
                files=self._agent_launcher_files(source_bin_dir, bin_dir, agent),
            )
        self.install_bundle(bundle, dry_run=dry_run, manifest=manifest)
