"""Source-of-truth specs for README diagrams rendered with ELK."""
from __future__ import annotations

from copy import deepcopy


def node(
    node_id: str,
    label: str,
    *,
    stroke: str = "#64748b",
    fill: str = "#ffffff",
    text: str = "#0f172a",
    width: int = 150,
    height: int = 52,
) -> dict:
    return {
        "kind": "node",
        "id": node_id,
        "label": label,
        "width": width,
        "height": height,
        "style": {"stroke": stroke, "fill": fill, "text": text},
    }


def group(
    group_id: str,
    label: str,
    children: list[dict],
    *,
    stroke: str,
    fill: str,
    text: str,
    direction: str = "RIGHT",
    padding: dict | None = None,
) -> dict:
    return {
        "kind": "group",
        "id": group_id,
        "label": label,
        "direction": direction,
        "padding": padding or {"top": 44, "right": 18, "bottom": 18, "left": 18},
        "style": {"stroke": stroke, "fill": fill, "text": text},
        "children": children,
    }


INDIGO = {"stroke": "#4f46e5", "fill": "#eef2ff", "text": "#1e1b4b"}
CYAN = {"stroke": "#0891b2", "fill": "#ecfeff", "text": "#164e63"}
SLATE = {"stroke": "#64748b", "fill": "#f8fafc", "text": "#334155"}
BLUE = {"stroke": "#2563eb", "fill": "#eff6ff", "text": "#1e3a8a"}
GREEN = {"stroke": "#16a34a", "fill": "#f0fdf4", "text": "#14532d"}
EMERALD = {"stroke": "#059669", "fill": "#ecfdf5", "text": "#064e3b"}
AMBER = {"stroke": "#d97706", "fill": "#fffbeb", "text": "#92400e"}
ORANGE = {"stroke": "#ea580c", "fill": "#fff7ed", "text": "#7c2d12"}
PURPLE = {"stroke": "#9333ea", "fill": "#faf5ff", "text": "#581c87"}
VIOLET = {"stroke": "#7c3aed", "fill": "#f5f3ff", "text": "#3b0764"}
PINK = {"stroke": "#db2777", "fill": "#fdf2f8", "text": "#831843"}
RED = {"stroke": "#dc2626", "fill": "#fef2f2", "text": "#7f1d1d"}
TEAL = {"stroke": "#0f766e", "fill": "#f0fdfa", "text": "#134e4a"}

GRAPH_SPECS: dict[str, dict] = {
    "runtime-map": {
        "direction": "RIGHT",
        "children": [
            node("repo", "repo checkout", **INDIGO),
            group(
                "plugin",
                "Plugin mode",
                [
                    node("plugin_cache", "plugin cache", **CYAN),
                    node("namespaced", "namespaced skills", width=182, **CYAN),
                ],
                direction="RIGHT",
                **CYAN,
            ),
            group(
                "workstation",
                "Workstation mode",
                [
                    node("installer", "install-assistant-tools", width=214, **ORANGE),
                    node("homes", "host homes", **BLUE),
                    node(
                        "agents",
                        "agents + worker dirs\nassistant / collab / coauthor",
                        width=246,
                        height=70,
                        **GREEN,
                    ),
                    node("tmux", "custom tmux", **GREEN),
                    node("profiles", "profiles", **BLUE),
                    node("hooks", "hooks", **PINK),
                    node("dispatcher", "dispatcher", **VIOLET),
                ],
                direction="RIGHT",
                padding={"top": 52, "right": 26, "bottom": 22, "left": 26},
                **SLATE,
            ),
        ],
        "edges": [
            {"source": "repo", "target": "plugin_cache"},
            {"source": "repo", "target": "installer"},
            {"source": "plugin_cache", "target": "namespaced", "hidden": True},
            {"source": "installer", "target": "homes"},
            {"source": "homes", "target": "agents"},
            {"source": "agents", "target": "tmux"},
            {"source": "tmux", "target": "profiles"},
            {"source": "profiles", "target": "hooks"},
            {"source": "hooks", "target": "dispatcher"},
        ],
    },
    "daily-assistant-loop": {
        "direction": "DOWN",
        "children": [
            group(
                "remote",
                "Remote data",
                [
                    node("mail", "email accounts", width=164, **BLUE),
                    node("calendar", "calendar", **BLUE),
                    node("weather", "weather", **BLUE),
                    group(
                        "drive",
                        "Google Drive",
                        [
                            node("remote_lists", "lists", **EMERALD),
                            node("remote_plans", "plans", **EMERALD),
                        ],
                        direction="RIGHT",
                        padding={"top": 40, "right": 14, "bottom": 14, "left": 14},
                        **EMERALD,
                    ),
                ],
                direction="RIGHT",
                **BLUE,
            ),
            group(
                "skills",
                "Skills",
                [
                    group(
                        "connectors",
                        "Cloud-facing skills",
                        [
                            node("email_client", "email-client", **CYAN),
                            node("g_calendar", "g-calendar", **CYAN),
                            node("get_weather", "get-weather", **CYAN),
                            node("cloud_files", "cloud-files", **CYAN),
                        ],
                        direction="RIGHT",
                        padding={"top": 40, "right": 14, "bottom": 14, "left": 14},
                        **CYAN,
                    ),
                    group(
                        "workflow",
                        "Local workflow skills",
                        [
                            node("email_triage", "email-triage", **ORANGE),
                            node("list_manager", "list-manager", **ORANGE),
                            node("daily_plan", "daily-plan", **ORANGE),
                            node("wrap_up", "wrap-up", **ORANGE),
                            node("recurring", "recurring-tasks", width=170, **ORANGE),
                        ],
                        direction="RIGHT",
                        padding={"top": 40, "right": 14, "bottom": 14, "left": 14},
                        **ORANGE,
                    ),
                ],
                direction="DOWN",
                **AMBER,
            ),
            group(
                "system",
                "Local system",
                [
                    node("systemd", "systemd timers", width=170, **RED),
                    node("logs", "logs + health", width=166, **RED),
                ],
                direction="RIGHT",
                **RED,
            ),
        ],
        "edges": [
            {"source": "mail", "target": "email_client", "bidirectional": True},
            {"source": "calendar", "target": "g_calendar"},
            {"source": "weather", "target": "get_weather"},
            {"source": "cloud_files", "target": "remote_lists", "bidirectional": True},
            {"source": "cloud_files", "target": "remote_plans", "bidirectional": True},
            {"source": "email_client", "target": "email_triage"},
            {"source": "email_triage", "target": "list_manager"},
            {"source": "list_manager", "target": "cloud_files", "bidirectional": True},
            {"source": "g_calendar", "target": "daily_plan"},
            {"source": "get_weather", "target": "daily_plan"},
            {"source": "daily_plan", "target": "cloud_files", "bidirectional": True},
            {"source": "wrap_up", "target": "daily_plan"},
            {"source": "wrap_up", "target": "list_manager"},
            {"source": "recurring", "target": "systemd"},
            {"source": "systemd", "target": "email_triage"},
            {"source": "systemd", "target": "daily_plan"},
            {"source": "systemd", "target": "logs"},
            {"source": "logs", "target": "recurring"},
            {"source": "mail", "target": "calendar", "hidden": True},
            {"source": "calendar", "target": "weather", "hidden": True},
            {"source": "weather", "target": "remote_lists", "hidden": True},
            {"source": "remote_lists", "target": "remote_plans", "hidden": True},
            {"source": "email_client", "target": "g_calendar", "hidden": True},
            {"source": "g_calendar", "target": "get_weather", "hidden": True},
            {"source": "get_weather", "target": "cloud_files", "hidden": True},
            {"source": "remote_plans", "target": "email_client", "hidden": True},
            {"source": "cloud_files", "target": "email_triage", "hidden": True},
            {"source": "email_triage", "target": "list_manager", "hidden": True},
            {"source": "list_manager", "target": "daily_plan", "hidden": True},
            {"source": "daily_plan", "target": "wrap_up", "hidden": True},
            {"source": "wrap_up", "target": "recurring", "hidden": True},
            {"source": "systemd", "target": "logs", "hidden": True},
        ],
    },
    "research-writing": {
        "direction": "DOWN",
        "children": [
            group(
                "inputs",
                "Inputs",
                [
                    node("draft", "draft", **SLATE),
                    node("tex", "TeX project", **SLATE),
                    node("pdf", "PDF", **SLATE),
                    node("bib", "BibTeX", **SLATE),
                    node("proof_text", "proof text", **SLATE),
                ],
                direction="RIGHT",
                **SLATE,
            ),
            group(
                "skills",
                "Research and writing skills",
                [
                    group(
                        "text",
                        "Text",
                        [
                            node("flow", "flow review", width=170, **GREEN),
                            node("prose", "prose review", width=170, **GREEN),
                        ],
                        direction="RIGHT",
                        padding={"top": 40, "right": 14, "bottom": 14, "left": 14},
                        **GREEN,
                    ),
                    group(
                        "structural",
                        "Structural",
                        [
                            node("latex", "latex-workshop", width=170, **BLUE),
                            node("dep_graph", "math-dep graph", width=170, **BLUE),
                            node("tex_doc", "TeX docstring", width=170, **BLUE),
                            node("pdf_md", "PDF to Markdown", width=182, **BLUE),
                            node("bib_audit", "bib-audit", width=170, **BLUE),
                        ],
                        direction="RIGHT",
                        padding={"top": 40, "right": 14, "bottom": 14, "left": 14},
                        **BLUE,
                    ),
                    group(
                        "math",
                        "Math-focused",
                        [
                            node("proof_audit", "proof-audit", width=170, **ORANGE),
                            node("tool_app", "tool fit", width=170, **ORANGE),
                            node("notation", "notation-review", width=170, **ORANGE),
                        ],
                        direction="RIGHT",
                        padding={"top": 40, "right": 14, "bottom": 14, "left": 14},
                        **ORANGE,
                    ),
                ],
                direction="DOWN",
                **PURPLE,
            ),
        ],
        "edges": [
            {"source": "draft", "target": "flow"},
            {"source": "draft", "target": "prose"},
            {"source": "tex", "target": "latex"},
            {"source": "tex", "target": "dep_graph"},
            {"source": "tex", "target": "tex_doc"},
            {"source": "pdf", "target": "pdf_md"},
            {"source": "bib", "target": "bib_audit"},
            {"source": "proof_text", "target": "proof_audit"},
            {"source": "proof_text", "target": "tool_app"},
            {"source": "proof_text", "target": "notation"},
            {"source": "draft", "target": "tex", "hidden": True},
            {"source": "tex", "target": "pdf", "hidden": True},
            {"source": "pdf", "target": "bib", "hidden": True},
            {"source": "bib", "target": "proof_text", "hidden": True},
            {"source": "flow", "target": "prose", "hidden": True},
            {"source": "latex", "target": "dep_graph", "hidden": True},
            {"source": "dep_graph", "target": "tex_doc", "hidden": True},
            {"source": "tex_doc", "target": "pdf_md", "hidden": True},
            {"source": "pdf_md", "target": "bib_audit", "hidden": True},
            {"source": "proof_audit", "target": "tool_app", "hidden": True},
            {"source": "tool_app", "target": "notation", "hidden": True},
        ],
    },
    "skill-development-framework": {
        "direction": "RIGHT",
        "children": [
            group(
                "standards",
                "Shared standards",
                [
                    node("guidelines", "skill guidelines", width=190, **INDIGO),
                    node("blueprint_ref", "blueprint reference", width=190, **INDIGO),
                ],
                direction="RIGHT",
                **INDIGO,
            ),
            group(
                "skilldev",
                "Skill-development skills",
                [
                    node("skill_maker", "skill-maker", width=190, **CYAN),
                    node("refactor", "refactor-skills", width=190, **CYAN),
                    node("update_guidelines", "update-skill-guidelines", width=230, **CYAN),
                    node("hook_maker", "hook-maker", width=190, **CYAN),
                ],
                direction="RIGHT",
                **CYAN,
            ),
            group(
                "artifacts",
                "Created / edited artifacts",
                [
                    group(
                        "skill_dir",
                        "Skill directory",
                        [
                            node("skill_file", "SKILL.md", width=174, **ORANGE),
                            node("blueprint", "blueprint.yaml", width=174, **ORANGE),
                            node("scripts", "scripts/", width=174, **ORANGE),
                        ],
                        direction="RIGHT",
                        padding={"top": 40, "right": 14, "bottom": 14, "left": 14},
                        **ORANGE,
                    ),
                    node("hook_files", "hook files", width=174, **ORANGE),
                ],
                direction="RIGHT",
                **ORANGE,
            ),
            group(
                "enforcement",
                "Mechanical enforcement",
                [
                    node("sync", "blueprint sync", width=182, **VIOLET),
                    node("generated", "generated blocks", width=182, **VIOLET),
                    node("dispatcher", "dispatcher", width=182, **VIOLET),
                    node("validators", "validators", width=182, **RED),
                    node("pre_commit", "pre-commit hook", width=182, **RED),
                    node("ci", "CI checks", width=182, **RED),
                ],
                direction="RIGHT",
                **RED,
            ),
        ],
        "edges": [
            {"source": "guidelines", "target": "skill_maker"},
            {"source": "guidelines", "target": "refactor"},
            {"source": "guidelines", "target": "update_guidelines"},
            {"source": "guidelines", "target": "hook_maker"},
            {"source": "blueprint_ref", "target": "skill_maker"},
            {"source": "blueprint_ref", "target": "refactor"},
            {"source": "blueprint_ref", "target": "update_guidelines"},
            {"source": "skill_maker", "target": "skill_file"},
            {"source": "skill_maker", "target": "blueprint"},
            {"source": "skill_maker", "target": "scripts"},
            {"source": "refactor", "target": "skill_file"},
            {"source": "refactor", "target": "blueprint"},
            {"source": "refactor", "target": "scripts"},
            {"source": "hook_maker", "target": "hook_files"},
            {"source": "update_guidelines", "target": "guidelines"},
            {"source": "update_guidelines", "target": "blueprint_ref"},
            {"source": "update_guidelines", "target": "validators"},
            {"source": "blueprint", "target": "sync"},
            {"source": "sync", "target": "generated"},
            {"source": "generated", "target": "skill_file"},
            {"source": "blueprint", "target": "dispatcher"},
            {"source": "dispatcher", "target": "scripts"},
            {"source": "skill_file", "target": "validators"},
            {"source": "blueprint", "target": "validators"},
            {"source": "scripts", "target": "validators"},
            {"source": "hook_files", "target": "validators"},
            {"source": "validators", "target": "pre_commit"},
            {"source": "pre_commit", "target": "ci"},
            {"source": "guidelines", "target": "blueprint_ref", "hidden": True},
            {"source": "skill_maker", "target": "refactor", "hidden": True},
            {"source": "refactor", "target": "update_guidelines", "hidden": True},
            {"source": "update_guidelines", "target": "hook_maker", "hidden": True},
            {"source": "skill_file", "target": "blueprint", "hidden": True},
            {"source": "blueprint", "target": "scripts", "hidden": True},
            {"source": "scripts", "target": "hook_files", "hidden": True},
            {"source": "sync", "target": "generated", "hidden": True},
            {"source": "generated", "target": "dispatcher", "hidden": True},
            {"source": "dispatcher", "target": "validators", "hidden": True},
            {"source": "validators", "target": "pre_commit", "hidden": True},
            {"source": "pre_commit", "target": "ci", "hidden": True},
        ],
    },
    "scaffolding-responsibility-map": {
        "direction": "RIGHT",
        "children": [
            group(
                "llm_work",
                "LLM building the assistant",
                [node("prompt", "write / edit a skill", width=196, **INDIGO)],
                direction="RIGHT",
                **INDIGO,
            ),
            group(
                "convention",
                "Convention scaffold",
                [
                    node("skill_maker_entry", "skill-maker", width=174, **CYAN),
                    node("guideline_ref", "skill guidelines", width=174, **CYAN),
                    node("template_ref", "blueprint template", width=182, **CYAN),
                ],
                direction="DOWN",
                **CYAN,
            ),
            group(
                "owned_surfaces",
                "Owned skill surfaces",
                [
                    node("skill_md_surface", "SKILL.md", width=170, **ORANGE),
                    node("blueprint_surface", "blueprint.yaml", width=170, **ORANGE),
                    node("scripts_surface", "scripts/", width=170, **ORANGE),
                ],
                direction="DOWN",
                **ORANGE,
            ),
            group(
                "mechanics",
                "Mechanical enforcement",
                [
                    node("sync_surface", "blueprint sync", width=182, **VIOLET),
                    node("dispatcher_surface", "dispatcher", width=182, **VIOLET),
                    node("validators_surface", "validators", width=182, **RED),
                    node("precommit_surface", "pre-commit + CI", width=182, **RED),
                ],
                direction="DOWN",
                **RED,
            ),
            group(
                "outcomes",
                "End goals",
                [
                    node("cohesive_goal", "cohesive skills", width=182, **GREEN),
                    node("boundary_goal", "narrow touch surface", width=196, **GREEN),
                    node("mistake_goal", "flagged LLM mistakes", width=196, **GREEN),
                    node("overlap_goal", "lower tool overlap", width=182, **GREEN),
                ],
                direction="DOWN",
                **GREEN,
            ),
        ],
        "edges": [
            {"source": "prompt", "target": "skill_maker_entry"},
            {"source": "guideline_ref", "target": "skill_maker_entry"},
            {"source": "template_ref", "target": "blueprint_surface"},
            {"source": "skill_maker_entry", "target": "skill_md_surface"},
            {"source": "skill_maker_entry", "target": "blueprint_surface"},
            {"source": "skill_maker_entry", "target": "scripts_surface"},
            {"source": "blueprint_surface", "target": "sync_surface"},
            {"source": "sync_surface", "target": "skill_md_surface"},
            {"source": "blueprint_surface", "target": "dispatcher_surface"},
            {"source": "dispatcher_surface", "target": "scripts_surface"},
            {"source": "skill_md_surface", "target": "validators_surface"},
            {"source": "blueprint_surface", "target": "validators_surface"},
            {"source": "scripts_surface", "target": "validators_surface"},
            {"source": "validators_surface", "target": "precommit_surface"},
            {"source": "skill_md_surface", "target": "cohesive_goal"},
            {"source": "blueprint_surface", "target": "boundary_goal"},
            {"source": "precommit_surface", "target": "mistake_goal"},
            {"source": "dispatcher_surface", "target": "overlap_goal"},
            {"source": "guideline_ref", "target": "template_ref", "hidden": True},
            {"source": "skill_md_surface", "target": "blueprint_surface", "hidden": True},
            {"source": "blueprint_surface", "target": "scripts_surface", "hidden": True},
            {"source": "sync_surface", "target": "dispatcher_surface", "hidden": True},
            {"source": "dispatcher_surface", "target": "validators_surface", "hidden": True},
            {"source": "cohesive_goal", "target": "boundary_goal", "hidden": True},
            {"source": "boundary_goal", "target": "mistake_goal", "hidden": True},
            {"source": "mistake_goal", "target": "overlap_goal", "hidden": True},
        ],
    },
    "skill-taxonomy": {
        "direction": "DOWN",
        "children": [
            group(
                "assistant",
                "assistant",
                [
                    group(
                        "research",
                        "research",
                        [
                            node("bib-audit", "bib-audit", **BLUE),
                            node("formal-prose-review", "formal-prose-review", width=182, **BLUE),
                            node("latex-workshop", "latex-workshop", **BLUE),
                            node("make-tex-docstring", "make-tex-docstring", width=182, **BLUE),
                            node("math-dependency-graph", "math-dependency-graph", width=192, **BLUE),
                            node("notation-review", "notation-review", **BLUE),
                            node("proof-audit", "proof-audit", **BLUE),
                            node("technical-flow-review", "technical-flow-review", width=192, **BLUE),
                        ],
                        direction="RIGHT",
                        **BLUE,
                    ),
                    group(
                        "general",
                        "general",
                        [
                            group(
                                "productivity",
                                "productivity",
                                [
                                    node("email-client", "email-client", **CYAN),
                                    node("email-triage", "email-triage", **CYAN),
                                    node("g-calendar", "g-calendar", **CYAN),
                                    node("get-weather", "get-weather", **CYAN),
                                    node("list-manager", "list-manager", **CYAN),
                                ],
                                direction="RIGHT",
                                padding={"top": 38, "right": 12, "bottom": 12, "left": 12},
                                **CYAN,
                            ),
                            group(
                                "workflow",
                                "workflow",
                                [
                                    node("daily-plan", "daily-plan", **ORANGE),
                                    node("find-handoff-candidates", "find-handoff-candidates", width=210, **ORANGE),
                                    node("loose-mode", "loose-mode", **ORANGE),
                                    node("prepare-handoff", "prepare-handoff", width=174, **ORANGE),
                                    node("tight-mode", "tight-mode", **ORANGE),
                                    node("tool-applicability", "tool-applicability", width=182, **ORANGE),
                                    node("wrap-up", "wrap-up", **ORANGE),
                                ],
                                direction="RIGHT",
                                padding={"top": 38, "right": 12, "bottom": 12, "left": 12},
                                **ORANGE,
                            ),
                        ],
                        direction="DOWN",
                        **AMBER,
                    ),
                ],
                direction="DOWN",
                padding={"top": 52, "right": 18, "bottom": 18, "left": 18},
                **TEAL,
            ),
            group(
                "development",
                "development",
                [
                    node("git-workflow", "git-workflow", **VIOLET),
                    group(
                        "skill",
                        "skill",
                        [
                            node("hook-maker", "hook-maker", **PINK),
                            node("install-assistant-tools", "install-assistant-tools", width=214, **PINK),
                            node("refactor-skills", "refactor-skills", **PINK),
                            node("skill-drift", "skill-drift", **PINK),
                            node("skill-maker", "skill-maker", **PINK),
                            node("update-skill-guidelines", "update-skill-guidelines", width=214, **PINK),
                        ],
                        direction="RIGHT",
                        padding={"top": 38, "right": 12, "bottom": 12, "left": 12},
                        **PINK,
                    ),
                    group(
                        "coding",
                        "coding",
                        [node("initialize-tdd", "initialize-tdd", **INDIGO)],
                        direction="RIGHT",
                        padding={"top": 38, "right": 12, "bottom": 12, "left": 12},
                        **INDIGO,
                    ),
                ],
                direction="DOWN",
                padding={"top": 52, "right": 18, "bottom": 18, "left": 18},
                **VIOLET,
            ),
            group(
                "system",
                "system",
                [
                    node("cloud-files", "cloud-files", **RED),
                    node("fix-bisync", "fix-bisync", **RED),
                    node("pdf-to-markdown", "pdf-to-markdown", width=174, **RED),
                    node("recurring-tasks", "recurring-tasks", width=174, **RED),
                ],
                direction="RIGHT",
                padding={"top": 52, "right": 18, "bottom": 18, "left": 18},
                **RED,
            ),
        ],
        "edges": [
            {"source": "bib-audit", "target": "formal-prose-review", "hidden": True},
            {"source": "formal-prose-review", "target": "latex-workshop", "hidden": True},
            {"source": "latex-workshop", "target": "make-tex-docstring", "hidden": True},
            {"source": "math-dependency-graph", "target": "notation-review", "hidden": True},
            {"source": "notation-review", "target": "proof-audit", "hidden": True},
            {"source": "proof-audit", "target": "technical-flow-review", "hidden": True},
            {"source": "email-client", "target": "email-triage", "hidden": True},
            {"source": "email-triage", "target": "g-calendar", "hidden": True},
            {"source": "g-calendar", "target": "get-weather", "hidden": True},
            {"source": "get-weather", "target": "list-manager", "hidden": True},
            {"source": "daily-plan", "target": "find-handoff-candidates", "hidden": True},
            {"source": "find-handoff-candidates", "target": "loose-mode", "hidden": True},
            {"source": "loose-mode", "target": "prepare-handoff", "hidden": True},
            {"source": "tight-mode", "target": "tool-applicability", "hidden": True},
            {"source": "tool-applicability", "target": "wrap-up", "hidden": True},
            {"source": "technical-flow-review", "target": "email-client", "hidden": True},
            {"source": "list-manager", "target": "daily-plan", "hidden": True},
            {"source": "wrap-up", "target": "git-workflow", "hidden": True},
            {"source": "hook-maker", "target": "install-assistant-tools", "hidden": True},
            {"source": "install-assistant-tools", "target": "refactor-skills", "hidden": True},
            {"source": "refactor-skills", "target": "skill-drift", "hidden": True},
            {"source": "skill-drift", "target": "skill-maker", "hidden": True},
            {"source": "skill-maker", "target": "update-skill-guidelines", "hidden": True},
            {"source": "git-workflow", "target": "hook-maker", "hidden": True},
            {"source": "update-skill-guidelines", "target": "initialize-tdd", "hidden": True},
            {"source": "initialize-tdd", "target": "cloud-files", "hidden": True},
            {"source": "cloud-files", "target": "fix-bisync", "hidden": True},
            {"source": "fix-bisync", "target": "pdf-to-markdown", "hidden": True},
            {"source": "pdf-to-markdown", "target": "recurring-tasks", "hidden": True},
        ],
    },
}


def build_specs() -> dict[str, dict]:
    return deepcopy(GRAPH_SPECS)
