#!/usr/bin/env python3
"""Regenerate the skills table in README.md from skills/*/.

Source of truth per skill:
  - skills/<name>/blueprint.yaml  -> category
  - skills/<name>/SKILL.md        -> frontmatter description (first sentence)

The table is written between the marker comments in README.md; everything
else in the file is left untouched. Run by .githooks/pre-commit so the table
can never go stale.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
README = REPO_ROOT / "README.md"

BEGIN = "<!-- BEGIN SKILLS TABLE (generated by scripts/generate-skills-table.py) -->"
END = "<!-- END SKILLS TABLE -->"

CATEGORY_TITLES = {
    "productivity-general-assistant": "Productivity",
    "workflow-general-assistant": "Workflow",
    "research-assistant": "Research & Writing",
    "system-assistant": "System & Automation",
    "development-assistant": "Development",
    "coding-development-assistant": "Development",
    "skill-making-development-assistant": "Skill Framework",
}

CATEGORY_ORDER = [
    "Productivity",
    "Workflow",
    "Research & Writing",
    "System & Automation",
    "Development",
    "Skill Framework",
]


def _frontmatter(skill_md: Path) -> dict:
    text = skill_md.read_text(encoding="utf-8")
    match = re.match(r"\A---\n(.*?)\n---\n", text, re.DOTALL)
    if not match:
        return {}
    data = yaml.safe_load(match.group(1))
    return data if isinstance(data, dict) else {}


# Hand-written summaries where the SKILL.md trigger-phrase reads poorly as
# prose. New skills fall back to an auto-summary of their description.
SUMMARY_OVERRIDES = {
    "bib-audit": "Audit a `.bib` file for validity, style, external metadata, and duplicates",
    "cloud-files": "Bounded read/write of plain files under a configured Google Drive root",
    "daily-plan": "Generate today's plan from calendar, todos, and weather",
    "email-client": "Read, search, and send email across configured accounts",
    "email-triage": "Triage the inbox into todo and potential-action lists since the last run",
    "fix-bisync": "Diagnose and repair rclone bisync failures",
    "formal-prose-review": "Polish grammar, tone, and concision in technical prose without touching the math",
    "proof-audit": "Audit a proof for soundness, coherence, hidden assumptions, and redundancy",
    "g-calendar": "Read and modify Google Calendar via a local OAuth CLI",
    "get-weather": "Fetch weather for a location, day, or date range",
    "git-workflow": "Branch-safety checks and commit hygiene for any repo",
    "hook-maker": "Design cross-host assistant hooks: one purpose, per-host bindings",
    "initialize-tdd": "Scaffold a staged, approval-gated TDD project",
    "install-assistant-tools": "Install or update launchers, wiring, hooks, and environment on a machine",
    "list-manager": "Manage personal YAML lists (todo, shopping, reading, …) in cloud storage",
    "loose-mode": "Broad, fast exploration mode — breadth over certainty",
    "math-dependency-graph": "Extract an assumptions-to-results dependency graph from a LaTeX document",
    "skill-maker": "Author new skills that conform to the repo's skill-writing guideline",
    "pdf-to-markdown": "Convert a research-paper PDF into LLM-readable text",
    "prepare-handoff": "Prepare a clean handoff: workflow updates, doc updates, residual lessons",
    "recurring-tasks": "Manage AI-driven recurring jobs as systemd user timers, with healthcheck",
    "refactor-skills": "Audit and refactor existing skills against local conventions",
    "tight-mode": "Rigorous, verified output mode — certainty over speed",
    "tool-applicability": "Check whether a theorem or framework achieves a target in the current setting",
    "update-skill-guidelines": "Change the skill-writing standard and its mechanical checks in lockstep",
    "wrap-up": "End-of-day wrap-up: review the plan, record completions, capture new items",
}

_TRIGGER_PREFIXES = [
    r"use whenever the user\s",
    r"use when the user (?:asks|wants|invokes|refers)\s(?:to\s|about\s)?",
    r"use when asked to\s",
    r"use when\s",
    r"use this skill to\s",
    r"use\s",
]


def _summary(description: str) -> str:
    """First sentence, trigger-phrase boilerplate stripped, single line."""
    flat = " ".join(description.split())
    sentence = re.split(r"(?<=[.!?])\s", flat, maxsplit=1)[0]
    lowered = sentence.lower()
    for prefix in _TRIGGER_PREFIXES:
        match = re.match(prefix, lowered)
        if match:
            sentence = sentence[match.end():]
            break
    sentence = sentence.strip().rstrip(".")
    if sentence:
        sentence = sentence[0].upper() + sentence[1:]
    if len(sentence) > 140:
        sentence = sentence[:140].rsplit(" ", 1)[0].rstrip(",;:") + " …"
    return sentence.replace("|", "\\|")


def build_table() -> str:
    grouped: dict[str, list[tuple[str, str]]] = {}
    for blueprint_path in sorted((REPO_ROOT / "skills").glob("*/blueprint.yaml")):
        skill_dir = blueprint_path.parent
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            continue
        blueprint = yaml.safe_load(blueprint_path.read_text(encoding="utf-8")) or {}
        category_slug = str(blueprint.get("category", ""))
        title = CATEGORY_TITLES.get(category_slug, category_slug or "Uncategorized")
        summary = SUMMARY_OVERRIDES.get(skill_dir.name)
        if summary is None:
            description = str(_frontmatter(skill_md).get("description", "")).strip()
            summary = _summary(description)
        grouped.setdefault(title, []).append((skill_dir.name, summary))

    lines: list[str] = []
    ordered = [t for t in CATEGORY_ORDER if t in grouped]
    ordered += [t for t in sorted(grouped) if t not in ordered]
    for title in ordered:
        lines.append(f"### {title}")
        lines.append("")
        lines.append("| Skill | What it does |")
        lines.append("|---|---|")
        for name, summary in grouped[title]:
            lines.append(f"| `{name}` | {summary} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"error: skills-table markers not found in {README}", file=sys.stderr)
        return 1
    prefix, rest = text.split(BEGIN, 1)
    _, suffix = rest.split(END, 1)
    new_text = f"{prefix}{BEGIN}\n{build_table()}{END}{suffix}"
    if new_text != text:
        README.write_text(new_text, encoding="utf-8")
        print("README.md skills table regenerated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
